export const blackWidowAnalysisSource = {
  sourceName: "New Rockstars-style Black Widow Analysis",
  sourceType: "analysis",
  reliability: "interpretive_context",
  rules: {
    canonFacts: "Verify against Marvel.com",
    productionMetadata: "Verify against IMDb",
    theories: "Label as theory or analysis",
  },
  timeline: [
    {
      period: "Pre-MCU",
      from: 1942,
      to: 2009,
      era: "Red Room Origin",
      character: "Natasha Romanoff",
      systemRole: "WEAPON_ORIGIN_BLACK_WIDOW",
      sourceTag: "analysis",
      movies: [],
      summary: "Natasha is shaped by the Red Room into an elite assassin, losing parts of her childhood and identity before beginning the long path toward reclaiming herself.",
      themes: ["control", "loss of identity", "manipulation", "trauma", "conditioning"],
    },
    {
      period: "2010-2012",
      from: 2010,
      to: 2012,
      era: "SHIELD Agent",
      character: "Natasha Romanoff",
      systemRole: "SPY_TO_HERO",
      sourceTag: "analysis",
      movies: ["Iron Man 2 (2010)", "The Avengers (2012)"],
      summary: "Natasha enters the story as a covert S.H.I.E.L.D. operative, then becomes one of the founding Avengers as her arc moves from spy work toward open heroism.",
      themes: ["redemption begins", "trust-building", "spy vs hero", "loyalty"],
    },
    {
      period: "2014-2015",
      from: 2013,
      to: 2015,
      era: "Moral Conflict",
      character: "Natasha Romanoff",
      systemRole: "GRAY_MORALITY_AGENT",
      sourceTag: "analysis",
      movies: ["Captain America: The Winter Soldier (2014)"],
      summary: "Natasha navigates secrets, shifting loyalties, and the collapse of S.H.I.E.L.D., balancing survival instincts with a stronger moral center.",
      themes: ["trust vs deception", "survival", "moral ambiguity", "hidden past"],
    },
    {
      period: "2016",
      from: 2016,
      to: 2017,
      era: "Closure Story",
      character: "Natasha Romanoff",
      systemRole: "TRAUMA_RESOLUTION",
      sourceTag: "analysis",
      movies: ["Captain America: Civil War (2016)", "Black Widow (2021)"],
      summary: "After Civil War, Natasha confronts the Red Room, her forced family history, and the control system that created her, turning the solo film into emotional closure rather than a simple origin story.",
      themes: ["chosen family", "trauma healing", "identity recovery", "breaking control systems"],
    },
    {
      period: "2018-2019",
      from: 2018,
      to: 2023,
      era: "Sacrifice",
      character: "Natasha Romanoff",
      systemRole: "SACRIFICE_BLACK_WIDOW",
      sourceTag: "analysis",
      movies: ["Avengers: Infinity War (2018)", "Avengers: Endgame (2019)"],
      summary: "Natasha becomes a central Avengers leader after the Snap and ultimately sacrifices herself on Vormir so the team can bring everyone back.",
      themes: ["sacrifice", "redemption completed", "loyalty", "chosen family bonds"],
    },
    {
      period: "Post-2019",
      from: 2024,
      to: 2027,
      era: "Legacy",
      character: "Yelena Belova",
      systemRole: "LEGACY_BLACK_WIDOW",
      sourceTag: "analysis",
      movies: ["Black Widow (2021)", "Hawkeye (2021)"],
      summary: "Natasha's legacy continues through Yelena, making Black Widow feel less like one codename and more like a recovered identity shared by survivors of the Red Room.",
      themes: ["legacy", "sisterhood", "continuation of identity", "healing beyond trauma"],
    },
  ],
  coreModel: {
    sourceTag: "analysis",
    identity: "A former weapon seeking redemption and identity through sacrifice and chosen family.",
    structure: "Redemption-driven hero grounded in emotional survival rather than superpowers.",
    themes: ["redemption", "identity", "trauma", "control vs freedom", "chosen family", "sacrifice"],
    narrativePatterns: ["weapon to human", "past trauma shaping present choices", "moral gray zones", "loyalty over ideology", "sacrifice as final redemption"],
  },
};

export const analysisForBlackWidowYear = (year) => blackWidowAnalysisSource.timeline.find((entry) => year >= entry.from && year <= entry.to) ?? null;
