export const captainAmericaAnalysisSource = {
  sourceName: "New Rockstars-style Captain America Analysis",
  sourceType: "analysis",
  reliability: "interpretive_context",
  rules: {
    canonFacts: "Verify against Marvel.com",
    productionMetadata: "Verify against IMDb",
    theories: "Label as theory or analysis",
  },
  timeline: [
    {
      period: "1940s",
      from: 1942,
      to: 1945,
      era: "Origin",
      character: "Steve Rogers",
      systemRole: "ORIGIN_CAPTAIN_AMERICA",
      sourceTag: "analysis",
      movies: ["Captain America: The First Avenger (2011)"],
      summary: "Steve Rogers becomes Captain America during World War II, turning from a rejected recruit into a symbol of idealism, duty, and sacrifice.",
      themes: ["duty", "sacrifice", "patriotism", "idealism", "war"],
    },
    {
      period: "Modern Awakening",
      from: 1946,
      to: 2013,
      era: "Displaced Hero",
      character: "Steve Rogers",
      systemRole: "DISPLACED_HERO",
      sourceTag: "analysis",
      movies: ["Captain America: The First Avenger (2011)", "The Avengers (2012)"],
      summary: "Steve is frozen in ice and wakes up decades later as a man out of time, carrying old ideals into a world that has changed around him.",
      themes: ["time displacement", "identity crisis", "loneliness", "adapting to modern world"],
    },
    {
      period: "2014",
      from: 2014,
      to: 2015,
      era: "Winter Soldier",
      character: "Steve Rogers",
      systemRole: "ANTI_SYSTEM_CAPTAIN_AMERICA",
      sourceTag: "analysis",
      movies: ["Captain America: The Winter Soldier (2014)"],
      summary: "Captain America exposes HYDRA inside S.H.I.E.L.D., shifting the symbol away from blind patriotism and toward resistance against corrupted authority.",
      themes: ["freedom vs control", "government corruption", "surveillance", "trust vs authority"],
    },
    {
      period: "2016",
      from: 2016,
      to: 2017,
      era: "Civil War",
      character: "Steve Rogers",
      systemRole: "IDEOLOGICAL_LEADER",
      sourceTag: "analysis",
      movies: ["Captain America: Civil War (2016)"],
      summary: "Steve opposes government control over heroes, choosing personal morality and loyalty over institutional obedience.",
      themes: ["freedom vs regulation", "personal responsibility", "loyalty", "moral conflict"],
    },
    {
      period: "2018-2019",
      from: 2018,
      to: 2020,
      era: "Endgame",
      character: "Steve Rogers",
      systemRole: "LEGACY_TRANSFER",
      sourceTag: "analysis",
      movies: ["Avengers: Infinity War (2018)", "Avengers: Endgame (2019)"],
      summary: "Steve completes his arc by helping defeat Thanos, choosing a full life in the past, and passing the shield to Sam Wilson.",
      themes: ["completion", "legacy", "sacrifice fulfilled", "passing the mantle"],
    },
    {
      period: "2021-present",
      from: 2021,
      to: 2027,
      era: "Sam Wilson Era",
      character: "Sam Wilson",
      systemRole: "SYMBOL_EVOLUTION_CAPTAIN_AMERICA",
      sourceTag: "analysis",
      movies: ["The Falcon and the Winter Soldier (2021)", "Captain America: Brave New World (2025)"],
      summary: "The Captain America symbol evolves through Sam Wilson, becoming less about one perfect soldier and more about what the shield means in a modern social and political world.",
      themes: ["identity", "representation", "responsibility", "modern politics", "what the symbol means"],
    },
  ],
  coreModel: {
    sourceTag: "analysis",
    identity: "A symbol of ideals that changes meaning depending on who carries the shield.",
    structure: "Legacy-based hero passed between individuals.",
    themes: ["freedom", "responsibility", "identity", "sacrifice", "authority vs morality", "national vs personal values"],
    narrativePatterns: ["weak man becomes strong", "symbol outlives the person", "ideals vs institutions", "mantle transfer"],
  },
};

export const analysisForCaptainAmericaYear = (year) => captainAmericaAnalysisSource.timeline.find((entry) => year >= entry.from && year <= entry.to) ?? null;
