export const hulkAnalysisSource = {
  sourceName: "New Rockstars-style Hulk Analysis",
  sourceType: "analysis",
  reliability: "interpretive_context",
  rules: {
    canonFacts: "Verify against Marvel.com",
    productionMetadata: "Verify against IMDb",
    theories: "Label as theory or analysis",
  },
  timeline: [
    {
      period: "2008",
      from: 2005,
      to: 2011,
      era: "Origin",
      character: "Bruce Banner / Hulk",
      systemRole: "ORIGIN_HULK",
      sourceTag: "analysis",
      movies: ["The Incredible Hulk (2008)"],
      summary: "Bruce Banner's gamma accident turns him into the Hulk, creating a frightening split between his intellect and a powerful emotional survival response.",
      themes: ["science gone wrong", "loss of control", "dual identity", "fear of self"],
    },
    {
      period: "2012-2015",
      from: 2012,
      to: 2016,
      era: "Uncontrolled Phase",
      character: "Bruce Banner / Hulk",
      systemRole: "UNCONTROLLED_FORCE",
      sourceTag: "analysis",
      movies: ["The Avengers (2012)", "Avengers: Age of Ultron (2015)"],
      summary: "Hulk is powerful but feared, while Bruce struggles to manage a transformation that can save people or destroy everything around him.",
      themes: ["rage vs control", "fear of power", "isolation", "inner conflict"],
    },
    {
      period: "2017",
      from: 2017,
      to: 2017,
      era: "Ragnarok",
      character: "Hulk",
      systemRole: "DUAL_IDENTITY_HULK",
      sourceTag: "analysis",
      movies: ["Thor: Ragnarok (2017)"],
      summary: "On Sakaar, Hulk stays in control long enough to feel like his own person, making the Banner/Hulk split feel less like a switch and more like two competing identities.",
      themes: ["identity separation", "Banner vs Hulk", "independence of Hulk", "self-awareness"],
    },
    {
      period: "2018-2019",
      from: 2018,
      to: 2023,
      era: "Integration",
      character: "Smart Hulk",
      systemRole: "INTEGRATED_HULK",
      sourceTag: "analysis",
      movies: ["Avengers: Infinity War (2018)", "Avengers: Endgame (2019)"],
      summary: "After Hulk refuses to fight, Bruce finds a new balance by merging Banner's mind with Hulk's body, then uses that strength to help reverse the Snap.",
      themes: ["integration", "acceptance of self", "mind and body balance", "growth through conflict"],
    },
    {
      period: "Post-2019",
      from: 2024,
      to: 2027,
      era: "Stability",
      character: "Professor Hulk",
      systemRole: "STABLE_HULK",
      sourceTag: "analysis",
      movies: ["She-Hulk: Attorney at Law (2022)"],
      summary: "Banner's Hulk form becomes more stable, shifting the character from chaos and fear toward mentorship, control, and the legacy of gamma-powered people.",
      themes: ["stability", "mentorship", "evolution beyond conflict", "legacy of power"],
    },
  ],
  coreModel: {
    sourceTag: "analysis",
    identity: "A man divided between intellect and rage, seeking balance between control and chaos.",
    structure: "Dual-identity psychological hero.",
    themes: ["control vs chaos", "identity fragmentation", "rage and emotion", "science vs humanity", "acceptance of self"],
    narrativePatterns: ["experiment to transformation", "loss of control to fear", "conflict between identities", "integration of dual selves", "balance replaces conflict"],
  },
};

export const analysisForHulkYear = (year) => hulkAnalysisSource.timeline.find((entry) => year >= entry.from && year <= entry.to) ?? null;
