export const ironManAnalysisSource = {
  sourceName: "New Rockstars-style Iron Man Analysis",
  sourceType: "analysis",
  reliability: "interpretive_context",
  rules: {
    canonFacts: "Verify against Marvel.com",
    productionMetadata: "Verify against IMDb",
    theories: "Label as theory or analysis",
  },
  timeline: [
    {
      period: "2008",
      from: 2010,
      to: 2010,
      era: "Origin",
      character: "Tony Stark",
      systemRole: "ORIGIN_IRON_MAN",
      sourceTag: "analysis",
      movies: ["Iron Man (2008)"],
      summary: "Tony Stark builds the first Iron Man suit after captivity, beginning his shift from selfish weapons industrialist to responsible hero and launching the MCU's core identity.",
      themes: ["responsibility through consequence", "technology vs morality", "redemption", "birth of hero identity"],
    },
    {
      period: "2010-2013",
      from: 2011,
      to: 2014,
      era: "Identity Conflict",
      character: "Tony Stark",
      systemRole: "IDENTITY_IRON_MAN",
      sourceTag: "analysis",
      movies: ["Iron Man 2 (2010)", "The Avengers (2012)", "Iron Man 3 (2013)"],
      summary: "Tony struggles with identity, legacy, trauma, and dependence on the suit, moving toward the idea that he is Iron Man with or without the armor.",
      themes: ["identity vs technology", "PTSD and trauma", "dependency vs self-worth", "man vs machine"],
    },
    {
      period: "2015-2016",
      from: 2015,
      to: 2017,
      era: "Control Phase",
      character: "Tony Stark",
      systemRole: "CONTROL_IRON_MAN",
      sourceTag: "analysis",
      movies: ["Avengers: Age of Ultron (2015)", "Captain America: Civil War (2016)"],
      summary: "Tony becomes focused on preventing future disasters, creating Ultron and later supporting superhero regulation, which puts his worldview in direct conflict with Captain America.",
      themes: ["control vs freedom", "fear of failure", "responsibility at scale", "moral compromise"],
    },
    {
      period: "2018-2019",
      from: 2018,
      to: 2023,
      era: "Sacrifice",
      character: "Tony Stark",
      systemRole: "SACRIFICE_IRON_MAN",
      sourceTag: "analysis",
      movies: ["Avengers: Infinity War (2018)", "Avengers: Endgame (2019)"],
      summary: "Tony faces the trauma of losing to Thanos, then completes his arc by sacrificing himself with the Infinity Stones to save the universe.",
      themes: ["sacrifice", "legacy", "redemption completed", "saving others at ultimate cost"],
    },
    {
      period: "Post-2019",
      from: 2024,
      to: 2027,
      era: "Legacy",
      character: "Tony Stark",
      systemRole: "LEGACY_IRON_MAN",
      sourceTag: "analysis",
      movies: [],
      summary: "After Tony's death, his technology, influence, mentorship, and moral choices continue to shape Spider-Man, the Avengers, and the MCU's larger mythology.",
      themes: ["legacy", "influence beyond death", "technological inheritance", "myth-building"],
    },
  ],
  coreModel: {
    sourceTag: "analysis",
    identity: "A flawed genius who evolves into a selfless protector through responsibility and sacrifice.",
    structure: "Foundational MCU character.",
    themes: ["responsibility", "redemption", "technology vs humanity", "ego vs sacrifice", "control vs chaos", "legacy"],
    narrativePatterns: ["arrogant genius to humbled hero", "technology creates solutions and problems", "ego vs responsibility", "sacrifice completes the arc", "legacy outlives the character"],
  },
};

export const analysisForIronManYear = (year) => ironManAnalysisSource.timeline.find((entry) => year >= entry.from && year <= entry.to) ?? null;
