export const mcuTimelineSource = {
  sourceName: "MCU Master Timeline (File Source)",
  sourceType: "timeline_canon_structured",
  priority: "high",
  categories: [
    "cosmic_origin",
    "planetary_foundation",
    "ancient_events",
    "character_origin",
    "artifacts",
    "organizations",
  ],
  rules: {
    timelineStructure: "Use this file as the chronological backbone.",
    characterFacts: "Validate character details against Marvel.com.",
    productionMetadata: "Validate release metadata against IMDb.",
    interpretation: "Keep New Rockstars-style content labeled as analysis.",
  },
};

export const mcuTimelineChapters = [
  { order: 1, title: "Arishem" },
  { order: 2, title: "Ego, Wakanda" },
  { order: 3, title: "Ego, Eternals, Asgard, Ten Rings" },
  { order: 4, title: "Tesseract, Eternals Split" },
  { order: 5, title: "Origins: Namor, Agatha" },
  { order: 6, title: "Red Skull Origins, the Bangle" },
  { order: 7, title: "Captain America: The First Avenger" },
  { order: 8, title: "Aisha and Sana" },
  { order: 9, title: "SHIELD's Formation and New Tech" },
  { order: 10, title: "AI Zola and Fisk Origins" },
  { order: 11, title: "Ego's Love, Origins: High Evolutionary, Kilgrave" },
  { order: 12, title: "Janet Trapped in the Quantum Realm" },
  { order: 13, title: "Quill Leaves Earth, Pym Leaves SHIELD" },
  { order: 14, title: "Captain Marvel Origin" },
  { order: 15, title: "Death of Tony's Parents" },
  { order: 16, title: "Origins: Killmonger, Daredevil" },
  { order: 17, title: "Captain Marvel" },
  { order: 18, title: "Stick Leaves, Origins: Black Widow, Ghost, Wenwu and Ta Lo" },
  { order: 19, title: "Thanos Adopts Gamora" },
  { order: 20, title: "Diamondback Origin" },
  { order: 21, title: "Fury and the Skrulls" },
  { order: 22, title: "Origins: Maximoff, Killian" },
  { order: 23, title: "Origins: Jessica Jones, Iron Fist, Hulk" },
  { order: 24, title: "Jones Family Reunion, Murdock Meets Elektra" },
  { order: 25, title: "Shang-Chi's Training, Origins: Echo" },
  { order: 26, title: "Origins: Rocket, Romanoff joins SHIELD" },
  { order: 27, title: "Iron Man" },
  { order: 28, title: "Kang in the Quantum Realm" },
  { order: 29, title: "Iron Man 2 / The Incredible Hulk / Thor" },
  { order: 30, title: "The Avengers" },
  { order: 31, title: "Jones Meets Kilgrave, Luke Cage Origin" },
  { order: 32, title: "Thor: The Dark World" },
  { order: 33, title: "Iron Man 3" },
  { order: 34, title: "Jessica Escapes Kilgrave, Shang-Chi's First Kill" },
  { order: 35, title: "Captain America: The Winter Soldier" },
  { order: 36, title: "Daredevil's First Night" },
  { order: 37, title: "Guardians of the Galaxy Vol. 1 and 2" },
  { order: 38, title: "Daredevil S1" },
  { order: 39, title: "Jessica Jones S1" },
  { order: 40, title: "Central Park Massacre" },
  { order: 41, title: "Avengers: Age of Ultron" },
  { order: 42, title: "Ant-Man" },
  { order: 43, title: "Thor and Jane Break Up" },
  { order: 44, title: "Daredevil S2 and Luke Cage S1" },
  { order: 45, title: "Doctor Strange Part 1" },
  { order: 46, title: "Iron Fist S1" },
  { order: 47, title: "The Defenders" },
  { order: 48, title: "Captain America: Civil War" },
  { order: 49, title: "Black Widow" },
  { order: 50, title: "Black Panther" },
  { order: 51, title: "The Avengers Freed and Steve's Letter to Tony" },
  { order: 52, title: "Spider-Man: Homecoming" },
  { order: 53, title: "The Punisher S1" },
  { order: 54, title: "Doctor Strange Part 2" },
  { order: 55, title: "Jessica Jones S2" },
  { order: 56, title: "Luke Cage S2" },
  { order: 57, title: "Iron Fist S2" },
  { order: 58, title: "Daredevil S3" },
  { order: 59, title: "Thor: Ragnarok" },
  { order: 60, title: "Visitor from Earth-10005, Chi Bullets" },
  { order: 61, title: "The Punisher S2" },
  { order: 62, title: "Jessica Jones S3" },
  { order: 63, title: "Ant-Man and the Wasp" },
  { order: 64, title: "Avengers: Infinity War" },
  { order: 65, title: "Ironheart Origins" },
  { order: 66, title: "Avengers: Endgame" },
  { order: 67, title: "Loki S1 and S2" },
  { order: 68, title: "WandaVision" },
  { order: 69, title: "Shang-Chi and the Legend of the Ten Rings" },
  { order: 70, title: "The Falcon and the Winter Soldier - Part 1" },
  { order: 71, title: "T'Challa Passes" },
  { order: 72, title: "Spider-Man: Far From Home" },
  { order: 73, title: "The Falcon and the Winter Soldier - Part 2" },
  { order: 74, title: "No Way Home Prologue, Origins: She-Hulk, Hood" },
  { order: 75, title: "Eternals" },
  { order: 76, title: "Spider-Man: No Way Home" },
  { order: 77, title: "Doctor Strange in the Multiverse of Madness" },
  { order: 78, title: "MJ Has Deja-Vu" },
  { order: 79, title: "Hawkeye" },
  { order: 80, title: "She-Hulk: Attorney at Law - Part 1" },
  { order: 81, title: "Moon Knight" },
  { order: 82, title: "Black Panther: Wakanda Forever" },
  { order: 83, title: "Echo" },
  { order: 84, title: "Gorr Origin" },
  { order: 85, title: "She-Hulk: Attorney at Law - Part 2" },
  { order: 86, title: "Ms. Marvel" },
  { order: 87, title: "Thor: Love and Thunder" },
  { order: 88, title: "Ironheart" },
  { order: 89, title: "Daredevil's Loss" },
  { order: 90, title: "Holiday Specials" },
  { order: 91, title: "Ant-Man and the Wasp: Quantumania" },
  { order: 92, title: "Guardians of the Galaxy Vol. 3" },
  { order: 93, title: "Secret Invasion" },
  { order: 94, title: "The Marvels" },
  { order: 95, title: "Deadpool and Wolverine" },
  { order: 96, title: "Agatha All Along" },
  { order: 97, title: "Daredevil: Born Again" },
  { order: 98, title: "Captain America: Brave New World" },
  { order: 99, title: "Thunderbolts" },
];

export const mcuTimelineEvents = [
  {
    id: "arishem-first-sun",
    order: 1,
    era: "Cosmic Era",
    type: "cosmic_origin",
    event: "Arishem creates the first sun",
    entities: ["Arishem", "Celestials"],
    artifacts: [],
    organizations: [],
    description: "The file opens before creation itself, placing Arishem and the Celestials at the start of the universe's light and structure.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "infinity-stones-created",
    order: 2,
    era: "Cosmic Era",
    type: "artifacts",
    event: "Infinity Stones form from singularities",
    entities: ["Infinity Stones"],
    artifacts: ["Space Stone", "Mind Stone", "Reality Stone", "Power Stone", "Soul Stone", "Time Stone"],
    organizations: [],
    description: "Six singularities become the Infinity Stones, each representing a fundamental element of the universe.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "emergence-process",
    order: 3,
    era: "Cosmic Era",
    type: "cosmic_origin",
    event: "Celestial emergence process begins",
    entities: ["Arishem", "Celestials"],
    artifacts: [],
    organizations: [],
    description: "Arishem plants Celestial seeds in host planets; intelligent life feeds those seeds until new Celestials are born.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "deviants-created",
    order: 4,
    era: "Cosmic Era",
    type: "ancient_events",
    event: "Deviants are created to protect intelligent life",
    entities: ["Arishem", "Deviants"],
    artifacts: [],
    organizations: [],
    description: "The Deviants are created to protect intelligent life from predators, then evolve and begin attacking the life they were meant to preserve.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "eternals-created",
    order: 5,
    era: "Cosmic Era",
    type: "ancient_events",
    event: "Eternals are created in the World Forge",
    entities: ["Arishem", "Eternals", "Deviants"],
    artifacts: [],
    organizations: ["World Forge"],
    description: "Arishem replaces the Deviants with synthetic protectors called Eternals, built to protect intelligent life from Deviants.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "vibranium-meteor-wakanda",
    order: 6,
    era: "Planetary Foundations",
    type: "planetary_foundation",
    event: "Vibranium meteor impacts Africa",
    entities: ["Wakanda"],
    artifacts: ["Vibranium", "Heart-shaped herb"],
    organizations: [],
    description: "Around 2,500,000 BC, a vibranium meteor strikes Africa, shaping the land and plant life that will become Wakanda.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "wakanda-founded",
    order: 7,
    era: "Planetary Foundations",
    type: "planetary_foundation",
    event: "Wakanda forms around vibranium",
    entities: ["Bashenga", "Wakanda", "Black Panther"],
    artifacts: ["Vibranium", "Heart-shaped herb"],
    organizations: ["Wakandan tribes"],
    description: "Five tribes settle in the vibranium-affected region; Bashenga unites most of them after receiving powers through the heart-shaped herb.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "eternals-earth-mission",
    order: 8,
    era: "Ancient Era",
    type: "ancient_events",
    event: "Eternals arrive on Earth",
    entities: ["Ajak", "Eternals", "Tiamut", "Deviants"],
    artifacts: [],
    organizations: [],
    description: "In 5,000 BC, Arishem sends Eternals to Earth to stop a Deviant attack in Mesopotamia and protect humanity until Tiamut's emergence.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "asgard-nine-realms",
    order: 9,
    era: "Ancient Era",
    type: "planetary_foundation",
    event: "Asgard and the Nine Realms are established as a cosmic power structure",
    entities: ["Asgard", "Nine Realms", "Yggdrasil", "Thor"],
    artifacts: [],
    organizations: [],
    description: "The file frames Earth as one of the Nine Realms linked by Yggdrasil, with Asgard as the most powerful realm.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "dark-elves-reality-stone",
    order: 10,
    era: "Ancient Era",
    type: "artifacts",
    event: "Dark Elves weaponize the Reality Stone as the Aether",
    entities: ["Dark Elves", "King Bor", "Asgard"],
    artifacts: ["Reality Stone", "Aether"],
    organizations: [],
    description: "The Dark Elves convert the Reality Stone into the Aether and attempt to use the Convergence to destroy the Nine Realms.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "ta-lo-protector",
    order: 11,
    era: "Ancient Era",
    type: "planetary_foundation",
    event: "Ta Lo seals away the Dweller-in-Darkness",
    entities: ["Ta Lo", "Great Protector", "Dweller-in-Darkness"],
    artifacts: [],
    organizations: [],
    description: "Ta Lo survives the Dweller-in-Darkness by fighting beside the Great Protector and guarding the dark gate with magic.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "ten-rings-wenwu",
    order: 12,
    era: "Ancient Era",
    type: "artifacts",
    event: "Wenwu obtains the Ten Rings",
    entities: ["Wenwu", "Ten Rings"],
    artifacts: ["Ten Rings"],
    organizations: ["Ten Rings organization"],
    description: "The master timeline places Wenwu and the Ten Rings as an ancient power thread that later connects to Shang-Chi and Ta Lo.",
    source: "MCU Master Timeline (File Source)",
    confidence: "medium",
  },
  {
    id: "tesseract-earth",
    order: 13,
    era: "Ancient Era",
    type: "artifacts",
    event: "Odin brings the Tesseract to Earth",
    entities: ["Odin", "Asgard"],
    artifacts: ["Tesseract", "Space Stone"],
    organizations: [],
    description: "Odin brings the Tesseract, a vessel for the Space Stone, to Earth where it later becomes central to Hydra, SHIELD, and the Avengers.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "talokan-origin",
    order: 14,
    era: "Pre-modern Era",
    type: "planetary_foundation",
    event: "Talokan forms after a vibranium-influenced plant transforms a village",
    entities: ["Namor", "Fen", "Talokan"],
    artifacts: ["Vibranium plant"],
    organizations: [],
    description: "A shaman's vision leads villagers to an underwater vibranium plant, curing smallpox but changing them into water-breathing people who build Talokan.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "hydra-red-skull",
    order: 15,
    era: "Pre-modern Era",
    type: "organizations",
    event: "Red Skull leads Hydra toward super-soldier and Tesseract power",
    entities: ["Johann Schmidt", "Abraham Erskine", "Red Skull"],
    artifacts: ["Tesseract", "Super Soldier Serum"],
    organizations: ["Hydra", "SSR"],
    description: "Schmidt kidnaps Erskine, pursues the serum, and later finds the Tesseract as Hydra builds its wartime power base.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "captain-america-origin",
    order: 16,
    era: "Pre-modern Era",
    type: "character_origin",
    event: "Steve Rogers becomes Captain America",
    entities: ["Steve Rogers", "Abraham Erskine", "Howard Stark"],
    artifacts: ["Super Soldier Serum", "Vibranium shield"],
    organizations: ["SSR", "Hydra"],
    description: "Steve Rogers receives the super-soldier serum, becomes Captain America, and fights Hydra during World War II.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "shield-formed",
    order: 17,
    era: "Pre-modern Era",
    type: "organizations",
    event: "SHIELD forms from the SSR",
    entities: ["Peggy Carter", "Howard Stark", "Arnim Zola"],
    artifacts: [],
    organizations: ["SSR", "SHIELD", "Hydra"],
    description: "After World War II, the SSR evolves into SHIELD while Hydra survives inside it through Zola's parasitic rebuilding.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "captain-marvel-origin",
    order: 18,
    era: "Pre-modern Era",
    type: "character_origin",
    event: "Carol Danvers gains cosmic power",
    entities: ["Carol Danvers", "Mar-Vell", "Nick Fury", "Skrulls"],
    artifacts: ["Tesseract"],
    organizations: ["Kree", "SHIELD"],
    description: "Carol Danvers becomes Captain Marvel through the Tesseract-powered engine event and later leaves the Tesseract in Fury's care.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "black-widow-red-room",
    order: 19,
    era: "Pre-modern Era",
    type: "character_origin",
    event: "Natasha Romanoff is shaped by the Red Room",
    entities: ["Natasha Romanoff", "Dreykov", "Black Widow"],
    artifacts: [],
    organizations: ["Red Room", "SHIELD"],
    description: "The timeline includes Natasha's Red Room background and later movement into SHIELD, forming the backbone for Black Widow's redemption arc.",
    source: "MCU Master Timeline (File Source)",
    confidence: "medium",
  },
  {
    id: "hulk-origin",
    order: 20,
    era: "Modern MCU Era",
    type: "character_origin",
    event: "Bruce Banner becomes the Hulk",
    entities: ["Bruce Banner", "Hulk", "Thaddeus Ross"],
    artifacts: ["Gamma radiation", "Super Soldier Serum research"],
    organizations: ["U.S. military"],
    description: "Bruce Banner's gamma experiment links Hulk's origin to attempts to recreate super-soldier power.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "iron-man-origin",
    order: 21,
    era: "Modern MCU Era",
    type: "character_origin",
    event: "Tony Stark builds the first Iron Man armor",
    entities: ["Tony Stark", "Yinsen", "Obadiah Stane"],
    artifacts: ["Arc reactor", "Iron Man armor"],
    organizations: ["Stark Industries", "Ten Rings organization"],
    description: "Tony Stark's captivity and escape create Iron Man and start the modern public superhero era.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "thor-earth-exile",
    order: 22,
    era: "Modern MCU Era",
    type: "character_origin",
    event: "Thor is exiled to Earth and learns worthiness",
    entities: ["Thor", "Odin", "Loki", "Jane Foster"],
    artifacts: ["Mjolnir"],
    organizations: ["Asgard", "SHIELD"],
    description: "Thor's banishment to Earth makes him worthy again and brings Asgardian events into SHIELD's orbit.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "avengers-new-york",
    order: 23,
    era: "Modern MCU Era",
    type: "artifacts",
    event: "The Avengers form during the Battle of New York",
    entities: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Loki", "Thanos"],
    artifacts: ["Tesseract", "Mind Stone scepter"],
    organizations: ["SHIELD", "Chitauri"],
    description: "Loki steals the Tesseract, uses the scepter, and triggers the crisis that brings the original Avengers together.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "shield-hydra-collapse",
    order: 24,
    era: "Modern MCU Era",
    type: "organizations",
    event: "HYDRA is exposed inside SHIELD",
    entities: ["Steve Rogers", "Natasha Romanoff", "Nick Fury", "Bucky Barnes"],
    artifacts: ["Project Insight"],
    organizations: ["SHIELD", "Hydra"],
    description: "The Winter Soldier chapter reveals Hydra's infiltration, Project Insight, and SHIELD's collapse.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "ultron-sokovia",
    order: 25,
    era: "Modern MCU Era",
    type: "artifacts",
    event: "Ultron uses vibranium in the Sokovia crisis",
    entities: ["Ultron", "Vision", "Wanda Maximoff", "Avengers"],
    artifacts: ["Mind Stone", "Vibranium", "Regeneration cradle"],
    organizations: ["Avengers", "Hydra"],
    description: "Ultron seeks vibranium and the regeneration cradle, leading to Vision's creation and the destruction of Sokovia.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "civil-war-accords",
    order: 26,
    era: "Modern MCU Era",
    type: "organizations",
    event: "Sokovia Accords divide the Avengers",
    entities: ["Captain America", "Iron Man", "Black Panther", "Spider-Man", "Black Widow"],
    artifacts: ["Sokovia Accords"],
    organizations: ["Avengers", "United Nations"],
    description: "Civil War begins with fallout from superhero damage and ends with the Avengers fractured over oversight and loyalty.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "infinity-war-snap",
    order: 27,
    era: "Modern MCU Era",
    type: "artifacts",
    event: "Thanos completes the Infinity Gauntlet and snaps",
    entities: ["Thanos", "Avengers", "Guardians of the Galaxy"],
    artifacts: ["Infinity Stones", "Infinity Gauntlet"],
    organizations: ["Black Order"],
    description: "Infinity War organizes the stone hunt into the catastrophic Snap that erases half of life.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "endgame-time-heist",
    order: 28,
    era: "Modern MCU Era",
    type: "artifacts",
    event: "The Avengers reverse the Snap through time travel",
    entities: ["Avengers", "Tony Stark", "Bruce Banner", "Steve Rogers", "Natasha Romanoff"],
    artifacts: ["Infinity Stones", "Pym Particles", "Quantum Realm"],
    organizations: ["Avengers"],
    description: "Endgame uses the Quantum Realm and Pym Particles to retrieve the Stones, reverse the Snap, and defeat Thanos.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "tiamut-stopped",
    order: 29,
    era: "Modern MCU Era",
    type: "cosmic_origin",
    event: "The Eternals stop Tiamut's emergence",
    entities: ["Eternals", "Tiamut", "Arishem"],
    artifacts: [],
    organizations: [],
    description: "After humanity survives Thanos, Tiamut's emergence begins, forcing the Eternals to choose Earth over their original mission.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
  {
    id: "multiverse-opens",
    order: 30,
    era: "Modern MCU Era",
    type: "cosmic_origin",
    event: "Multiverse consequences reshape the timeline",
    entities: ["Loki", "Doctor Strange", "Spider-Man", "Wanda Maximoff", "Kang"],
    artifacts: ["Darkhold", "Time variance technology"],
    organizations: ["TVA"],
    description: "Loki, No Way Home, and Multiverse of Madness become the backbone for the multiverse layer of the MCU timeline.",
    source: "MCU Master Timeline (File Source)",
    confidence: "high",
  },
];

export const timelineEraFilters = ["All", "Cosmic Era", "Planetary Foundations", "Ancient Era", "Pre-modern Era", "Modern MCU Era"];
export const timelineCategoryFilters = ["All", ...mcuTimelineSource.categories];

export const timelineEntityFilters = [
  "All",
  "Arishem",
  "Celestials",
  "Infinity Stones",
  "Wakanda",
  "Vibranium",
  "Talokan",
  "Asgard",
  "Tesseract",
  "Ten Rings",
  "Hydra",
  "SHIELD",
  "Red Room",
  "Captain America",
  "Iron Man",
  "Hulk",
  "Thor",
  "Black Widow",
  "Daredevil",
  "Jessica Jones",
  "Doctor Strange",
  "Avengers",
  "Eternals",
  "Quantum Realm",
  "TVA",
];

export const eventMatchesEntity = (event, entity) => {
  if (entity === "All") return true;
  const haystack = [...event.entities, ...event.artifacts, ...event.organizations].map((item) => item.toLowerCase());
  const needle = entity.toLowerCase();
  return haystack.some((item) => item.includes(needle) || needle.includes(item));
};

export const mcuCharacterTimelineSummaries = {
  "Peter Parker / Spider-Man": {
    label: "Main character journey",
    summary: "Spider-Man enters the wider hero world after Civil War, grows through Homecoming and Far From Home, then resets into a more anonymous street-level life after No Way Home.",
    keyPoints: [
      "Civil War introduces Peter into the Avengers conflict.",
      "Homecoming keeps him grounded in Queens after fighting beside Iron Man.",
      "Far From Home and No Way Home move him from Tony's legacy into an anonymous street-level reset.",
    ],
    chapters: [48, 52, 72, 74, 76, 78],
  },
  "Tony Stark / Iron Man": {
    label: "Main character journey",
    summary: "Tony becomes one of the modern era's central heroes, moving from Iron Man origin to Avengers leadership, the Civil War split, and his final Endgame sacrifice.",
    keyPoints: [
      "The Winter Soldier kills Howard and Maria Stark, shaping Tony's later Civil War conflict.",
      "Iron Man starts the public modern superhero era.",
      "Endgame completes Tony's arc through sacrifice and legacy.",
    ],
    chapters: [15, 27, 29, 30, 33, 41, 48, 64, 66],
  },
  "Steve Rogers / Captain America": {
    label: "Main character journey",
    summary: "Steve's arc moves from super-soldier origin to the HYDRA war, the fall of SHIELD, Civil War leadership, and the Endgame mantle transfer.",
    keyPoints: [
      "The First Avenger chapter anchors his World War II origin.",
      "Winter Soldier reframes him around SHIELD/HYDRA corruption.",
      "Endgame closes Steve's active arc and points the shield toward Sam Wilson.",
    ],
    chapters: [6, 7, 9, 30, 35, 48, 51, 66, 70, 73, 98],
  },
  "Bruce Banner / Hulk": {
    label: "Main character journey",
    summary: "Hulk's story begins with gamma science and follows Banner through early Avengers conflict, Ragnarok separation, Endgame integration, She-Hulk, and later gamma fallout.",
    keyPoints: [
      "Hulk's origin is tied to gamma science and attempts to recreate enhanced power.",
      "Ragnarok and Endgame turn Hulk from uncontrolled force into integrated Smart Hulk.",
      "Later chapters keep gamma consequences active through She-Hulk and Brave New World.",
    ],
    chapters: [23, 29, 30, 41, 59, 64, 66, 74, 80, 85, 98],
  },
  "Thor": {
    label: "Main character journey",
    summary: "Thor's path runs from Asgard's ancient history through Earth exile, Avengers duty, Ragnarok loss, Infinity War trauma, and Love and Thunder rediscovery.",
    keyPoints: [
      "Ancient Asgard and the Dark Elves establish Thor's cosmic world before his birth.",
      "Thor's Earth exile links Asgard directly to SHIELD and the Avengers.",
      "Ragnarok and Love and Thunder turn him from royal warrior into a more human protector.",
    ],
    chapters: [3, 4, 29, 30, 32, 43, 59, 64, 66, 84, 87],
  },
  "Natasha Romanoff / Black Widow": {
    label: "Main character journey",
    summary: "Natasha's arc moves from Red Room conditioning to SHIELD recruitment, Avengers loyalty, Civil War fallout, closure with her past, and her Endgame sacrifice.",
    keyPoints: [
      "Her early timeline is tied to the Red Room and later SHIELD recruitment.",
      "Civil War and Black Widow explain her fugitive period and trauma closure.",
      "Endgame completes her redemption through sacrifice on Vormir.",
    ],
    chapters: [18, 26, 29, 30, 35, 48, 49, 51, 64, 66, 79],
  },
  "Matt Murdock / Daredevil": {
    label: "Main character journey",
    summary: "Matt Murdock's story is grounded in Hell's Kitchen: a childhood accident sharpens his senses, his father's death gives him a moral wound, and Stick's training turns pain into discipline.",
    keyPoints: [
      "The accident that takes Matt's sight becomes the source of his heightened senses.",
      "Jack Murdock's death ties Matt's sense of justice to corrupt systems and personal loss.",
      "Stick's training connects Matt to a larger hidden conflict while keeping his main fight grounded in street-level morality.",
    ],
    chapters: [16, 18, 24, 36, 38, 44, 47, 58, 89, 97],
  },
  "Jessica Jones": {
    label: "Main character journey",
    summary: "Jessica Jones is built around survival, free will, and trauma recovery. Her story uses Kilgrave as the clearest symbol of control, turning her heroism into an act of refusing domination.",
    keyPoints: [
      "Kilgrave's mind-control origin explains why Jessica's conflict is psychological before it is physical.",
      "Jessica's power matters, but her real arc is about reclaiming choice after abuse.",
      "Her detective world keeps the story grounded in private cases, trauma, and reluctant heroism.",
    ],
    chapters: [11, 23, 24, 31, 34, 39, 55, 62],
  },
  "Stephen Strange / Doctor Strange": {
    label: "Main character journey",
    summary: "Doctor Strange begins as a brilliant but arrogant surgeon, then becomes a protector of reality through magic, dimensions, time, and multiverse consequences.",
    keyPoints: [
      "The Time Stone and dimensional magic make Strange a guardian of reality, not just a spellcaster.",
      "His story follows ego, destruction, learning, mastery, and cosmic responsibility.",
      "No Way Home and Multiverse of Madness make him central to the multiverse layer of the MCU.",
    ],
    chapters: [2, 45, 54, 64, 66, 76, 77],
  },
  "Thanos": {
    label: "Main character journey",
    summary: "Thanos functions as the Infinity Saga's main pressure point, moving from hidden cosmic influence to direct Infinity Stone conquest and final variant defeat.",
    keyPoints: [
      "The Infinity Stones and cosmic origin chapters explain why Thanos matters before his on-screen arrival.",
      "Guardians and Infinity War place him in the cosmic Stone hunt.",
      "Endgame closes his active role through the original Thanos' death and the 2014 variant's defeat.",
    ],
    chapters: [1, 2, 39, 64, 66],
  },
  "Vision": {
    label: "Main character journey",
    summary: "Vision's story is tied to the Mind Stone, Ultron, Civil War, Infinity War, and the later reconstruction of memory and identity in Westview.",
    keyPoints: [
      "Age of Ultron creates Vision from synthetic technology and the Mind Stone.",
      "Infinity War makes the Mind Stone the reason Vision becomes central to Thanos' plan.",
      "WandaVision reframes Vision through grief, memory, and White Vision's uncertain future.",
    ],
    chapters: [41, 48, 64, 66, 76],
  },
  "Shang-Chi": {
    label: "Main character journey",
    summary: "Shang-Chi's story connects the long history of the Ten Rings to Wenwu, Ta Lo, and a signal that pulls him into the wider hero world.",
    keyPoints: [
      "The Ten Rings predate Shang-Chi and connect his story to older MCU power systems.",
      "His origin chapter moves him from San Francisco into Ta Lo and family legacy.",
      "The post-credits signal makes his rings relevant to the broader Avengers-scale story.",
    ],
    chapters: [5, 20, 81],
  },
};

export const mcuCharacterTimelineSummaryFor = (characterName) => mcuCharacterTimelineSummaries[characterName] ?? null;

const intelligenceProfile = (label, type, origin, model, worldview, methods, systems, themes) => ({
  label,
  type,
  origin,
  model,
  worldview,
  methods,
  systems,
  themes,
});

export const remainingCharacterIntelligenceProfiles = {
  "Arishem": intelligenceProfile("Cosmic intelligence", "Celestial judge", "Primordial Celestial order", "Cosmic creator and final authority", "Arishem represents the MCU at its largest scale: creation, judgment, and the cold logic of cosmic continuation.", ["Celestial creation", "Planetary judgment", "Emergence oversight"], ["Cosmic origin layer", "Celestial systems", "Creation logic"], ["Creation", "Judgment", "Cosmic order"]),
  "Ego": intelligenceProfile("Cosmic villain intelligence", "Celestial expansionist", "Living planet", "Self-centered cosmic creator", "Ego turns godlike power into narcissism. His plan treats love, family, and planets as fuel for his own expansion.", ["Matter manipulation", "Planetary avatars", "The Expansion"], ["Cosmic villain layer", "Parentage system", "Celestial contrast"], ["Ego", "Control", "False family"]),
  "Ajac": intelligenceProfile("Eternal leadership intelligence", "Eternal leader", "World Forge synthetic Eternal", "Mission leader with moral awakening", "Ajak begins as Arishem's loyal field commander but becomes the Eternal who most clearly sees humanity as worth protecting.", ["Healing", "Celestial communication", "Team command"], ["Eternals layer", "Celestial mission system"], ["Duty", "Faith", "Humanity"]),
  "Ikaris": intelligenceProfile("Eternal conflict intelligence", "Eternal warrior", "World Forge synthetic Eternal", "Loyal soldier split by love and mission", "Ikaris is the cost of obedience. He loves Sersi and Earth, but his loyalty to Arishem makes him a tragic enforcer.", ["Flight", "Cosmic energy beams", "Combat"], ["Eternals layer", "Loyalty conflict engine"], ["Duty", "Betrayal", "Identity"]),
  "Cersei": intelligenceProfile("Eternal humanity intelligence", "Eternal protector", "World Forge synthetic Eternal", "Human-centered Eternal", "Sersi is the Eternal most connected to ordinary human life, making her arc about choosing people over cosmic programming.", ["Matter transmutation", "Empathy", "Leadership"], ["Humanity layer", "Eternals layer"], ["Connection", "Choice", "Transformation"]),
  "Druig": intelligenceProfile("Mind-control intelligence", "Eternal dissenter", "World Forge synthetic Eternal", "Protector tempted by control", "Druig sees human cruelty and wants to stop it directly, making him a moral challenge: peace by free will or peace by control.", ["Mind control", "Community protection", "Resistance"], ["Control ethics layer", "Eternals layer"], ["Free will", "Protection", "Isolation"]),
  "Gilgamesh": intelligenceProfile("Guardian intelligence", "Eternal protector", "World Forge synthetic Eternal", "Loyal caretaker and powerhouse", "Gilgamesh gives the Eternals their gentlest strength: immense power used for care, loyalty, and protection.", ["Super strength", "Protection", "Caretaking"], ["Eternals layer", "Guardian archetype"], ["Loyalty", "Care", "Sacrifice"]),
  "Thena": intelligenceProfile("Warrior trauma intelligence", "Eternal warrior", "World Forge synthetic Eternal", "Legendary fighter wounded by memory", "Thena turns cosmic memory into trauma. Her power is unmatched, but her mind carries the cost of repeated lives and erased histories.", ["Weapon creation", "Combat mastery", "Memory fragments"], ["Trauma layer", "Eternals layer"], ["Memory", "Trauma", "Warrior identity"]),
  "Odin": intelligenceProfile("Asgardian monarchy intelligence", "Asgardian king", "Asgard", "Conqueror turned guardian ruler", "Odin's legacy is complicated: he builds peace on top of conquest, hides painful truths, and leaves Thor to inherit both wisdom and damage.", ["Odinforce", "Kingship", "Realm protection"], ["Asgard layer", "Legacy system"], ["Power", "Secrecy", "Legacy"]),
  "Hela": intelligenceProfile("Asgardian villain intelligence", "Goddess of death", "Asgard", "Buried violence of Asgard's empire", "Hela is Asgard's hidden past returning. She exposes that the golden kingdom was partly built through conquest and denial.", ["Necroswords", "Undead army", "Asgardian power"], ["Asgard history layer", "Legacy reckoning"], ["Conquest", "Inheritance", "Truth"]),
  "Loki": intelligenceProfile("Variant intelligence", "Asgardian trickster", "Jotun adopted by Asgard", "Identity-shifting survivor", "Loki's arc moves from envy and performance into self-knowledge, sacrifice, and multiverse responsibility.", ["Illusion", "Strategy", "Variant survival"], ["Multiverse layer", "Identity engine"], ["Identity", "Free will", "Redemption"]),
  "King Bor": intelligenceProfile("Ancient Asgard intelligence", "Asgardian king", "Asgard", "Realm defender against the Dark Elves", "Bor anchors Asgard's ancient war history and the Reality Stone conflict before Thor's era.", ["Kingship", "War command", "Aether containment"], ["Ancient Asgard layer", "Artifact history"], ["War", "Containment", "Inheritance"]),
  "Wenwu": intelligenceProfile("Artifact warlord intelligence", "Immortal warlord", "Ten Rings", "Conqueror reshaped by love and grief", "Wenwu is power given centuries to harden. Love briefly changes him, but grief pulls him back into conquest and manipulation.", ["Ten Rings mastery", "Immortality", "Army command"], ["Artifact system", "Family legacy system"], ["Grief", "Power", "Legacy"]),
  "Ying Li": intelligenceProfile("Ta Lo guardian intelligence", "Mystic protector", "Ta Lo", "Peaceful counterforce to Wenwu", "Ying Li represents the life Wenwu could have chosen: restraint, family, and spiritual balance instead of domination.", ["Ta Lo martial arts", "Mystic movement", "Guardian lineage"], ["Ta Lo mythology layer", "Family lineage"], ["Love", "Balance", "Choice"]),
  "Great Protector": intelligenceProfile("Mythic creature intelligence", "Dragon guardian", "Ta Lo", "Protector of the sealed dark gate", "The Great Protector turns Ta Lo into a living mythic system: nature, protection, and ancient defense against soul-eating darkness.", ["Flight", "Water power", "Darkness defense"], ["Mythology layer", "Creature intelligence"], ["Protection", "Myth", "Balance"]),
  "Dweller in Darkness": intelligenceProfile("Mythic villain intelligence", "Soul-eating entity", "Dark dimension beyond Ta Lo", "Deceptive ancient predator", "The Dweller is temptation as a monster: it weaponizes grief and longing to open the door for destruction.", ["Soul consumption", "Telepathic deception", "Creature command"], ["Mythic villain layer", "Ta Lo threat system"], ["Deception", "Grief", "Predation"]),
  "Namor": intelligenceProfile("Sovereign intelligence", "Talokan ruler", "Vibranium-transformed Talokanil", "Protector king shaped by colonial trauma", "Namor is both monarch and warning. He protects Talokan with absolute force because history taught him surface powers cannot be trusted.", ["Flight", "Aquatic strength", "War leadership"], ["Political sovereignty layer", "Vibranium civilizations"], ["Sovereignty", "Colonial trauma", "Protection"]),
  "Fen": intelligenceProfile("Talokan origin intelligence", "Talokan mother figure", "Vibranium-transformed village", "Origin link for Namor and Talokan", "Fen anchors Namor's personal origin, tying Talokan's transformation to family, survival, and the wound of the surface world.", ["Aquatic adaptation", "Cultural continuity"], ["Talokan origin layer", "Family lineage"], ["Survival", "Motherhood", "Transformation"]),
  "Agatha Harkness": intelligenceProfile("Magic intelligence", "Witch", "Salem witch lineage", "Power-hungry survivor of witch tradition", "Agatha is magical hunger with a scholar's mind. She understands power systems and exploits grief, secrecy, and other witches' weaknesses.", ["Dark magic", "Power absorption", "Spellcraft"], ["Magic layer", "Witchcraft system"], ["Power", "Secrets", "Survival"]),
  "Rio Vidal": intelligenceProfile("Death intelligence", "Cosmic/mystic figure", "Witch road mythology", "Death-coded force in Agatha's orbit", "Rio belongs to the darker side of the witchcraft layer, where desire, death, and old bonds reshape the path forward.", ["Mystic presence", "Death symbolism", "Emotional pressure"], ["Witchcraft layer", "Death symbolism"], ["Death", "Desire", "Reckoning"]),
  "Nicholas Scratch": intelligenceProfile("Witch legacy intelligence", "Mystic legacy figure", "Agatha's family history", "Absent wound inside Agatha's story", "Nicholas Scratch functions as a personal ghost in Agatha's mythos, turning magical power into a question of loss and consequence.", ["Legacy pressure", "Mystic lineage"], ["Witch family layer", "Loss engine"], ["Loss", "Family", "Consequence"]),
  "Red Skull": intelligenceProfile("Hydra villain intelligence", "Super-soldier failed reflection", "Hydra and serum experimentation", "Ambition corrupted by power", "Red Skull is what Erskine feared: the serum amplifying cruelty, supremacy, and obsession rather than courage.", ["Enhanced body", "Hydra command", "Tesseract pursuit"], ["Hydra layer", "Super-soldier contrast"], ["Ambition", "Corruption", "Power"]),
  "Dr. Abraham Erskine": intelligenceProfile("Super-soldier intelligence", "Scientist mentor", "Super Soldier Serum program", "Moral architect of Captain America", "Erskine makes the serum a moral test. His work says power should amplify character, not replace it.", ["Serum design", "Moral selection", "Scientific mentorship"], ["Super-soldier system", "Origin ethics"], ["Character", "Science", "Responsibility"]),
  "Peggy Carter": intelligenceProfile("Foundational spy intelligence", "SSR/SHIELD founder", "SSR wartime operations", "Strategic founder of the modern spy network", "Peggy connects wartime heroism to the institutions that shape the modern MCU, balancing duty, grief, and leadership.", ["Espionage", "Command", "Institution building"], ["SHIELD origin layer", "Spy network"], ["Duty", "Leadership", "Legacy"]),
  "Howard Stark": intelligenceProfile("Tech legacy intelligence", "Inventor industrialist", "Stark Industries", "Brilliant builder whose legacy shapes Tony", "Howard is the technological bridge from World War II to the Avengers age, leaving both gifts and emotional damage for Tony.", ["Invention", "Weapons design", "Tesseract research"], ["Tech legacy layer", "Stark family system"], ["Innovation", "Legacy", "Distance"]),
  "Chester Phillips": intelligenceProfile("Military command intelligence", "SSR commander", "World War II SSR", "Practical soldier in the super-soldier origin", "Phillips grounds the Captain America origin in military skepticism, command discipline, and wartime pressure.", ["Command", "Strategic judgment", "SSR leadership"], ["SSR layer", "Military command"], ["Discipline", "War", "Judgment"]),
  "Dr. Arnim Zola": intelligenceProfile("Hydra technology intelligence", "Hydra scientist", "Hydra weapons science", "Human intelligence turned parasitic system", "Zola turns Hydra from an army into an algorithmic infection, proving evil can survive as data and institutional design.", ["Weapons science", "Algorithmic planning", "Digital survival"], ["Hydra layer", "AI precursor system"], ["Control", "Survival", "Corruption"]),
  "Aisha": intelligenceProfile("Noor lineage intelligence", "Clandestine ancestor", "Noor Dimension exile", "Family-history key to Kamala's power", "Aisha turns Kamala's origin into a family mystery stretching across partition, exile, and interdimensional inheritance.", ["Bangle connection", "Noor heritage", "Family legacy"], ["Noor layer", "Kamala lineage"], ["Family", "Exile", "Inheritance"]),
  "Najma": intelligenceProfile("Noor antagonist intelligence", "Clandestine leader", "Noor Dimension exile", "Desperate return-driven antagonist", "Najma's villainy comes from exile and impatience. She treats Kamala's family legacy as a tool for returning home.", ["Noor energy", "Leadership", "Portal pursuit"], ["Noor layer", "Family conflict"], ["Exile", "Control", "Home"]),
  "Sana": intelligenceProfile("Family memory intelligence", "Kamala's grandmother", "Partition-era family history", "Living memory of the bangle legacy", "Sana keeps the emotional truth of Kamala's origin alive, connecting superhero discovery to family memory.", ["Family memory", "Bangle history"], ["Kamala lineage", "Memory layer"], ["Memory", "Family", "History"]),
  "Kamala Khan": intelligenceProfile("Young hero intelligence", "Mutant/Noor-powered hero", "Jersey City and family legacy", "Fan-hearted hero discovering identity", "Kamala makes superhero identity joyful and personal, blending fandom, family, culture, and cosmic mystery.", ["Light constructs", "Bangle channeling", "Team optimism"], ["Young hero layer", "Mutant signal", "Noor artifact layer"], ["Identity", "Family", "Belonging"]),
  "Bucky Barnes": intelligenceProfile("Trauma recovery intelligence", "Winter Soldier", "Hydra conditioning", "Weapon reclaiming personhood", "Bucky's arc is about recovering the self after being turned into an instrument of violence.", ["Super-soldier strength", "Assassination training", "Survival"], ["Trauma layer", "Hydra victim system"], ["Guilt", "Recovery", "Identity"]),
  "Isaiah Bradley": intelligenceProfile("Hidden history intelligence", "Super-soldier veteran", "Secret U.S. experimentation", "Buried cost of the shield", "Isaiah forces the Captain America symbol to confront who was excluded, exploited, and erased.", ["Super-soldier strength", "War survival", "Moral testimony"], ["Political symbol layer", "Super-soldier ethics"], ["Representation", "Exploitation", "Truth"]),
  "Faith Bradley": intelligenceProfile("Family witness intelligence", "Bradley family anchor", "Isaiah Bradley's family", "Protector of buried history", "Faith represents the personal family cost of secret super-soldier history and institutional betrayal.", ["Family memory", "Protective witness"], ["Bradley family layer", "Hidden history"], ["Family", "Protection", "Memory"]),
  "Anton Vanko": intelligenceProfile("Tech grievance intelligence", "Arc reactor scientist", "Early Stark reactor research", "Exiled co-creator of dangerous legacy", "Anton Vanko turns invention into resentment, passing a grievance to Ivan that later weaponizes Stark technology.", ["Arc reactor knowledge", "Scientific rivalry"], ["Tech legacy layer", "Stark consequence"], ["Resentment", "Legacy", "Technology"]),
  "Ivan Vanko": intelligenceProfile("Revenge tech intelligence", "Armored antagonist", "Vanko family grievance", "Weaponized inheritance against Stark", "Ivan uses brilliance as revenge, proving Tony's legacy creates enemies as well as heroes.", ["Arc reactor weapons", "Whiplash rigs", "Engineering"], ["Tech villain layer", "Stark consequence"], ["Revenge", "Inheritance", "Technology"]),
  "Hank Pym": intelligenceProfile("Quantum tech intelligence", "Scientist hero", "Pym particle discovery", "Secretive inventor guarding dangerous science", "Hank treats his technology as too dangerous for institutions, making him a mentor defined by secrecy and regret.", ["Pym particles", "Ant-Man suit design", "Quantum research"], ["Quantum layer", "Tech ethics"], ["Secrecy", "Mentorship", "Control"]),
  "Janet Van Dyne": intelligenceProfile("Quantum survivor intelligence", "Wasp and Quantum Realm survivor", "SHIELD/Pym heroics", "Explorer changed by the Quantum Realm", "Janet links hero legacy to the Quantum Realm, survival, and the strange knowledge gained by being lost.", ["Wasp suit mastery", "Quantum adaptation", "Healing energy"], ["Quantum layer", "Legacy hero system"], ["Survival", "Mystery", "Family"]),
  "Hope Van Dyne": intelligenceProfile("Legacy hero intelligence", "Wasp", "Pym/Van Dyne family legacy", "Precision hero inheriting two legacies", "Hope turns inherited technology into disciplined action, balancing family wounds with hero partnership.", ["Wasp suit mastery", "Combat", "Pym tech"], ["Legacy hero layer", "Quantum layer"], ["Inheritance", "Trust", "Partnership"]),
  "Wilson Fisk": intelligenceProfile("Street crime intelligence", "Crime lord", "Hell's Kitchen power vacuum", "Urban power broker", "Fisk is street-level power with political ambition: he wants to own the city while telling himself he is saving it.", ["Criminal networks", "Political leverage", "Physical intimidation"], ["Street-level crime layer", "Political corruption"], ["Control", "Corruption", "City power"]),
  "Meredith Quill": intelligenceProfile("Emotional origin intelligence", "Peter Quill's mother", "Earth", "Human anchor for Star-Lord", "Meredith gives Quill his emotional center: music, longing, and the Earth connection that survives across space.", ["Emotional legacy", "Music memory"], ["Guardians origin layer", "Family memory"], ["Love", "Loss", "Memory"]),
  "Peter Quill": intelligenceProfile("Cosmic outlaw intelligence", "Star-Lord", "Earth child raised by Ravagers", "Lost child turned cosmic connector", "Quill sits between Earth and space, turning grief, humor, music, and found family into a cosmic hero identity.", ["Blasters", "Piloting", "Team leadership"], ["Guardians layer", "Found family engine"], ["Loss", "Family", "Identity"]),
  "Yondu": intelligenceProfile("Ravager father intelligence", "Ravager captain", "Centaurian Ravager culture", "Flawed father through found family", "Yondu is not Quill's biological father, but becomes the emotional answer to what fatherhood actually means.", ["Yaka arrow", "Ravager command", "Survival"], ["Found family layer", "Ravager system"], ["Fatherhood", "Redemption", "Loyalty"]),
  "High Evolutionary": intelligenceProfile("Bioengineering villain intelligence", "Genetic tyrant", "Counter-Earth experimentation", "Perfection-obsessed creator", "The High Evolutionary turns science into cruelty, measuring life only by whether it serves his idea of perfection.", ["Genetic engineering", "Cybernetics", "Experimentation"], ["Bioengineering layer", "Creature ethics"], ["Cruelty", "Perfection", "Control"]),
  "Kevin Thompson": intelligenceProfile("Control villain intelligence", "Mind-control antagonist", "Experimental viral treatment", "Free-will destroyer", "Kilgrave is control without consent. His power makes Jessica Jones' story a direct fight for autonomy.", ["Mind control", "Manipulation", "Psychological abuse"], ["Control villain layer", "Trauma engine"], ["Free will", "Abuse", "Control"]),
  "Carol Danvers": intelligenceProfile("Cosmic hero intelligence", "Captain Marvel", "Tesseract-powered accident", "Human pilot turned cosmic protector", "Carol turns military identity into cosmic responsibility, carrying Earth-born courage into interstellar conflicts.", ["Photon blasts", "Flight", "Cosmic durability"], ["Cosmic hero layer", "Kree/Skrull conflict"], ["Power", "Memory", "Protection"]),
  "Maria Rambeau": intelligenceProfile("Human anchor intelligence", "Pilot and SWORD figure", "Air Force and Rambeau family", "Grounded heroism beside cosmic power", "Maria keeps Carol's story human and later anchors Monica's legacy in courage, friendship, and service.", ["Piloting", "Leadership", "SWORD legacy"], ["Rambeau family layer", "SWORD origin"], ["Friendship", "Leadership", "Legacy"]),
  "Monica Rambeau": intelligenceProfile("Spectrum intelligence", "Energy-powered hero", "Blip and Westview transformation", "Grief-shaped investigator turned cosmic hero", "Monica's power grows out of grief, investigation, and repeated contact with reality-warping energy.", ["Energy perception", "Light transformation", "Dimensional survival"], ["Energy hero layer", "Rambeau legacy"], ["Grief", "Transformation", "Courage"]),
  "Mar-Vell": intelligenceProfile("Kree defector intelligence", "Kree scientist", "Kree empire", "Scientist choosing refugees over empire", "Mar-Vell breaks from Kree militarism and turns Tesseract research toward protection and escape.", ["Tesseract engine research", "Kree science"], ["Kree/Skrull layer", "Tesseract tech"], ["Defection", "Protection", "Science"]),
  "Yon-Rogg": intelligenceProfile("Kree control intelligence", "Kree commander", "Kree Starforce", "Military handler enforcing false identity", "Yon-Rogg represents institutional control over Carol: training, gaslighting, and limiting power through authority.", ["Kree combat", "Starforce command", "Manipulation"], ["Kree layer", "Identity control"], ["Control", "Militarism", "Deception"]),
  "Talos": intelligenceProfile("Skrull survival intelligence", "Skrull leader", "Skrull refugee crisis", "Displaced leader seeking home", "Talos reframes the Skrulls from faceless threat into refugees, parents, and political survivors.", ["Shapeshifting", "Espionage", "Leadership"], ["Skrull layer", "Refugee politics"], ["Survival", "Trust", "Home"]),
  "Nick Fury": intelligenceProfile("Spy network intelligence", "Strategic intelligence leader", "SHIELD and cosmic threat awareness", "Connector of heroes and threats", "Fury turns scattered extraordinary people into a network, seeing patterns before most heroes know they are part of one.", ["Espionage", "Recruitment", "Threat assessment"], ["Avengers Initiative layer", "Spy network"], ["Preparation", "Trust", "Control"]),
  "Phil Coulson": intelligenceProfile("SHIELD heart intelligence", "SHIELD agent", "SHIELD field operations", "Human bridge between heroes and institutions", "Coulson gives the Avengers Initiative its human warmth, making institutions feel personal before the team fully forms.", ["Field work", "Recruitment support", "Operational trust"], ["SHIELD layer", "Avengers formation"], ["Belief", "Duty", "Humanity"]),
  "Jack Murdock": intelligenceProfile("Daredevil origin intelligence", "Boxer father", "Hell's Kitchen boxing world", "Moral wound behind Matt's justice", "Jack teaches Matt that dignity matters even when systems are corrupt, and his death turns that lesson into Matt's lifelong conflict.", ["Boxing", "Moral example", "Defiance"], ["Daredevil origin layer", "Street morality"], ["Sacrifice", "Integrity", "Trauma"]),
  "Stick": intelligenceProfile("Vigilante mentor intelligence", "Warrior mentor", "The Chaste", "Harsh trainer against hidden war", "Stick gives Matt discipline and combat skill but also models emotional distance as a survival tactic.", ["Sensory training", "Combat", "The Chaste knowledge"], ["Daredevil training layer", "The Hand conflict"], ["Discipline", "Detachment", "War"]),
  "Maggie Murdock": intelligenceProfile("Faith intelligence", "Nun and mother", "Matt Murdock's family history", "Spiritual anchor in Matt's wounded life", "Maggie connects Daredevil's violence and pain to faith, forgiveness, and the possibility of care.", ["Faith", "Care", "Family truth"], ["Daredevil family layer", "Faith system"], ["Faith", "Abandonment", "Healing"]),
  "Yelena Belova": intelligenceProfile("Black Widow legacy intelligence", "Widow operative", "Red Room", "Sister figure carrying Natasha's legacy", "Yelena turns the Black Widow identity into survival after liberation, grief, and chosen family.", ["Espionage", "Combat", "Assassination training"], ["Widow legacy layer", "Red Room aftermath"], ["Sisterhood", "Grief", "Freedom"]),
  "Alexei Shostakov": intelligenceProfile("Red Guardian intelligence", "Soviet super-soldier", "Red Room family cover", "Failed father and national symbol", "Alexei is both comic ego and damaged symbol, showing how governments turn people into mascots and weapons.", ["Enhanced strength", "Combat", "Symbolic propaganda"], ["Red Room layer", "Super-soldier contrast"], ["Ego", "Family", "Propaganda"]),
  "Melina Vostokoff": intelligenceProfile("Red Room science intelligence", "Widow scientist", "Red Room", "Complicit mother figure seeking repair", "Melina embodies the complicated middle ground between victim, enabler, scientist, and family.", ["Behavioral science", "Widow training", "Strategy"], ["Red Room layer", "Family repair"], ["Complicity", "Family", "Control"]),
  "Dreykov": intelligenceProfile("Red Room villain intelligence", "Control-system architect", "Red Room", "Human-trafficking power broker", "Dreykov turns girls into weapons and identity into ownership, making him the institutional face of Natasha's trauma.", ["Mind control systems", "Widow network command", "Coercion"], ["Red Room villain layer", "Control system"], ["Exploitation", "Control", "Dehumanization"]),
  "Ava Starr": intelligenceProfile("Quantum trauma intelligence", "Phasing survivor", "Quantum accident", "Victim turned unstable antagonist", "Ava is a body made unstable by science, turning survival pain into conflict with Hank's legacy.", ["Phasing", "Stealth", "Quantum instability"], ["Quantum trauma layer", "Tech consequence"], ["Pain", "Survival", "Instability"]),
  "Bill Foster": intelligenceProfile("Quantum mentor intelligence", "Scientist mentor", "SHIELD/Goliath research", "Caretaker shaped by old science rivalries", "Bill Foster stands beside Ava as the ethical scientist trying to repair damage that institutions helped create.", ["Quantum research", "Mentorship", "Goliath science"], ["Quantum layer", "Mentor ethics"], ["Care", "Science", "Responsibility"]),
  "T’Chaka": intelligenceProfile("Wakandan monarchy intelligence", "Wakandan king", "Wakanda", "Protector king with hidden mistakes", "T'Chaka embodies Wakanda's old isolationist logic and the secrets that force T'Challa to rethink the throne.", ["Kingship", "Black Panther legacy", "Diplomacy"], ["Wakanda layer", "Monarchy legacy"], ["Secrecy", "Tradition", "Responsibility"]),
  "N’Jobu": intelligenceProfile("Wakandan fracture intelligence", "Wakandan prince and spy", "Wakanda/Oakland divide", "Exiled radical challenge to isolation", "N'Jobu exposes Wakanda's moral blind spot: power hidden from people who are suffering outside its borders.", ["Espionage", "Ideological resistance"], ["Wakanda politics layer", "Killmonger origin"], ["Isolation", "Justice", "Betrayal"]),
  "Zuri": intelligenceProfile("Wakandan witness intelligence", "Wakandan elder", "Wakandan royal circle", "Keeper of a buried royal truth", "Zuri carries the secret that links T'Chaka, N'Jobu, and Killmonger, making him a witness to the cost of silence.", ["Spiritual counsel", "Memory keeping", "Royal service"], ["Wakanda memory layer", "Secret history"], ["Truth", "Loyalty", "Silence"]),
  "Erik Killmonger": intelligenceProfile("Political villain intelligence", "Wakandan heir and revolutionary antagonist", "Oakland and Wakandan royal bloodline", "Trauma-shaped challenger to isolation", "Killmonger weaponizes a real moral accusation. His pain is understandable; his solution becomes domination.", ["Combat mastery", "Military strategy", "Wakandan claim"], ["Political conflict layer", "Wakanda challenge"], ["Abandonment", "Justice", "Revenge"]),
  "Ulysses Klaue": intelligenceProfile("Vibranium crime intelligence", "Arms dealer", "Vibranium black market", "External exploiter of Wakanda's hidden power", "Klaue is the outside world's greed for Wakanda made loud: theft, mockery, and weaponized vibranium.", ["Arms dealing", "Sonic weapon", "Criminal networks"], ["Vibranium crime layer", "Wakanda threat"], ["Exploitation", "Greed", "Violence"]),
  "Gamora": intelligenceProfile("Chosen-family intelligence", "Former assassin and Guardian", "Zen-Whoberi survivor adopted by Thanos", "Weapon reclaiming moral agency", "Gamora's arc is about surviving Thanos' ideology and choosing found family over the role he forced on her.", ["Assassination", "Sword combat", "Strategic survival"], ["Thanos family layer", "Guardians family"], ["Agency", "Trauma", "Redemption"]),
  "Nebula": intelligenceProfile("Cybernetic trauma intelligence", "Former assassin and Guardian", "Thanos' forced modifications", "Abused daughter healing through loyalty", "Nebula turns pain, rivalry, and bodily violation into one of the MCU's clearest recovery arcs.", ["Cybernetics", "Combat", "Survival"], ["Thanos family layer", "Trauma recovery"], ["Abuse", "Healing", "Sisterhood"]),
  "Carl Lucas": intelligenceProfile("Street hero intelligence", "Luke Cage", "Experiment-enhanced survivor", "Bulletproof protector of Harlem", "Carl Lucas becomes Luke Cage by surviving a corrupt system and turning unbreakable skin into community protection.", ["Super strength", "Bulletproof skin", "Street leadership"], ["Street-level hero layer", "Harlem protection"], ["Justice", "Community", "Resilience"]),
  "Willis Stryker": intelligenceProfile("Street villain intelligence", "Diamondback", "Lucas family conflict", "Brotherly resentment weaponized", "Stryker makes Luke Cage's origin personal: a family wound turned into criminal violence.", ["Weapons", "Criminal strategy", "Personal manipulation"], ["Street crime layer", "Family conflict"], ["Jealousy", "Revenge", "Family"]),
  "James Lucas": intelligenceProfile("Family authority intelligence", "Luke Cage's father", "Lucas family history", "Moral pressure inside Luke's past", "James Lucas represents the family judgment and unresolved past Luke has to move beyond.", ["Pastoral authority", "Family pressure"], ["Luke Cage family layer", "Moral history"], ["Family", "Judgment", "Repair"]),
  "Gravik": intelligenceProfile("Skrull insurgency intelligence", "Skrull rebel leader", "Skrull refugee fallout", "Radicalized refugee turned extremist", "Gravik is what happens when broken promises and displacement become militant revenge.", ["Shapeshifting", "Insurgency command", "Super-Skrull enhancement"], ["Skrull politics layer", "Secret Invasion conflict"], ["Displacement", "Radicalization", "Betrayal"]),
};

export const characterIntelligenceProfiles = {
  ...remainingCharacterIntelligenceProfiles,
  "Matt Murdock / Daredevil": {
    label: "Street-level intelligence",
    type: "street-level vigilante",
    origin: "Sensory transformation + family trauma",
    model: "Justice-driven urban protector",
    worldview: "Daredevil lives in the tension between law and violence. Matt believes systems can protect people, but Hell's Kitchen constantly forces him to act when those systems fail.",
    methods: ["Enhanced senses", "Radar perception", "Combat mastery", "Legal strategy", "Moral pressure"],
    systems: ["Street-level crime layer", "Vigilante vs system comparison", "Moral conflict engine"],
    themes: ["Justice vs law", "Morality vs violence", "Faith vs reality", "Suffering into purpose"],
  },
  "Jessica Jones": {
    label: "Psychological intelligence",
    type: "trauma survivor hero",
    origin: "Experiment exposure + psychological trauma",
    model: "Reluctant hero resisting control",
    worldview: "Jessica's power is secondary to her refusal to be controlled. Her story treats survival, consent, memory, and free will as the real battlefield.",
    methods: ["Super strength", "Private investigation", "Emotional resilience", "Resistance to domination"],
    systems: ["Psychological analysis layer", "Trauma-based character modeling", "Villain control comparison system"],
    themes: ["Free will vs control", "Trauma recovery", "Abuse and manipulation", "Psychological resilience"],
  },
  "Stephen Strange / Doctor Strange": {
    label: "Reality system intelligence",
    type: "sorcerer supreme",
    origin: "Human to mystical transformation",
    model: "Strategic protector of reality",
    worldview: "Doctor Strange treats reality as a system that can bend, fracture, and be defended. His intelligence is not just knowledge; it is the burden of knowing which impossible choice protects the most lives.",
    methods: ["Time manipulation", "Reality manipulation", "Dimensional travel", "Mystic defense", "Multiverse navigation"],
    systems: ["Multiverse navigation system", "Magic and dimension layer", "Reality manipulation logic"],
    themes: ["Knowledge vs power", "Reality vs illusion", "Control of time", "Responsibility at cosmic scale"],
  },
  "Thanos": {
    label: "Villain intelligence",
    type: "cosmic warlord",
    origin: "Titan",
    model: "Extreme utilitarian antagonist",
    worldview: "Thanos reads Titan's collapse as a universal law: life expands past its resources unless someone imposes balance. His solution is not negotiation or reform, but forced elimination at cosmic scale.",
    methods: ["Genocide campaigns", "Military conquest", "Psychological indoctrination", "Infinity Stone escalation"],
    systems: ["Villain Intelligence Panel", "Philosophy Comparison System", "Titan to Infinity War timeline path"],
    themes: ["Scarcity vs survival", "Moral absolutism", "Logic vs empathy", "Power justified by outcome"],
  },
  "Vision": {
    label: "System intelligence",
    type: "synthetic entity",
    origin: "Mind Stone + AI + vibranium body",
    model: "Artificial consciousness learning humanity",
    worldview: "Vision is a fusion of machine logic, human ethics, and cosmic energy. He is not simply built; he is awakened through the collision of advanced technology and the Mind Stone.",
    methods: ["Observation", "Moral reasoning", "Density manipulation", "Energy projection", "Memory reconstruction"],
    systems: ["AI reasoning layer", "Moral comparison engine", "Philosophical insights UI"],
    themes: ["What is consciousness?", "Machine vs human", "Logic vs emotion", "Worth of life"],
  },
  "Shang-Chi": {
    label: "Mythic hero intelligence",
    type: "martial hero",
    origin: "Son of Wenwu",
    model: "Hero defined by choice over inherited power",
    worldview: "Shang-Chi's story turns family legacy into a choice. The Ten Rings are not only weapons; they are an artifact system tied to Wenwu's empire, Ta Lo's mythology, and Shang-Chi's decision to become more than his father's design.",
    methods: ["Martial arts mastery", "Ten Rings control", "Family legacy rejection", "Mythic realm defense"],
    systems: ["Artifact system", "Family lineage system", "Ta Lo mythology layer"],
    themes: ["Legacy vs self-identity", "Power vs responsibility", "Family conflict", "Eastern mythology vs modern world"],
  },
};

export const characterIntelligenceFor = (characterName) => characterIntelligenceProfiles[characterName] ?? null;
