export const spiderManAnalysisSource = {
  sourceName: "New Rockstars-style Spider-Man Analysis",
  sourceType: "analysis",
  reliability: "interpretive_context",
  rules: {
    canonFacts: "Verify against Marvel.com",
    productionMetadata: "Verify against IMDb",
    theories: "Label as theory or analysis",
  },
  timeline: [
    {
      period: "2002-2007",
      from: 2002,
      to: 2007,
      era: "Raimi Era",
      actor: "Tobey Maguire",
      systemRole: "FOUNDATION_SPIDER_MAN",
      sourceTag: "analysis",
      movies: ["Spider-Man (2002)", "Spider-Man 2 (2004)", "Spider-Man 3 (2007)"],
      summary: "Classic cinematic foundation focused on responsibility, sacrifice, Uncle Ben, and iconic villains.",
      themes: ["responsibility", "sacrifice", "personal loss", "hero duty"],
    },
    {
      period: "2012-2014",
      from: 2012,
      to: 2014,
      era: "Amazing Spider-Man Era",
      actor: "Andrew Garfield",
      systemRole: "SCIENTIFIC_SPIDER_MAN",
      sourceTag: "analysis",
      movies: ["The Amazing Spider-Man (2012)", "The Amazing Spider-Man 2 (2014)"],
      summary: "Science-focused reboot centered on Oscorp, genetics, Peter's parents, Gwen Stacy, and responsibility.",
      yearNotes: {
        2012: "Peter discovers his powers, investigates his parents' past, builds mechanical web-shooters, fights the Lizard, and shifts from revenge toward responsibility.",
      },
      themes: ["science", "genetics", "family mystery", "identity", "revenge to responsibility"],
    },
    {
      period: "2016-2019",
      from: 2016,
      to: 2019,
      era: "MCU Integration",
      actor: "Tom Holland",
      systemRole: "CONNECTED_SPIDER_MAN",
      sourceTag: "analysis",
      movies: ["Captain America: Civil War (2016)", "Spider-Man: Homecoming (2017)", "Spider-Man: Far From Home (2019)"],
      summary: "Spider-Man enters the MCU, is mentored by Tony Stark, uses high-tech suits, and learns independence.",
      themes: ["mentorship", "technology", "Avengers connection", "coming of age"],
    },
    {
      period: "2021",
      from: 2021,
      to: 2021,
      era: "Multiverse Event",
      actor: "Tom Holland / Tobey Maguire / Andrew Garfield",
      systemRole: "MULTIVERSE_CORE_EVENT",
      sourceTag: "analysis",
      movies: ["Spider-Man: No Way Home (2021)"],
      summary: "Three cinematic Spider-Men converge, multiverse villains return, and Tom Holland's Peter is reset.",
      themes: ["multiverse", "legacy", "identity loss", "redemption"],
    },
    {
      period: "2022-2026",
      from: 2022,
      to: 2026,
      era: "Grounded Reset",
      actor: "Tom Holland",
      systemRole: "GROUNDED_RESET_SPIDER_MAN",
      sourceTag: "analysis",
      movies: [],
      summary: "Peter becomes independent, unknown, street-level, and closer to the classic friendly neighborhood Spider-Man.",
      themes: ["independence", "street-level heroism", "isolation", "rebuilding"],
    },
  ],
  coreModel: {
    sourceTag: "analysis",
    identity: "Young hero balancing responsibility, personal loss, identity, and hero duty.",
    structure: "Multiverse character with several cinematic versions.",
    environment: "Primarily a street-level New York hero.",
    themes: ["responsibility", "sacrifice", "identity", "personal loss", "science", "multiverse", "street-level heroism"],
    narrativePatterns: ["spider bite origin", "loss creates responsibility", "science-based villains", "mentor figures", "love interest conflict", "secret identity pressure"],
  },
};

export const analysisForSpiderManYear = (year) => spiderManAnalysisSource.timeline.find((entry) => year >= entry.from && year <= entry.to) ?? null;
