export const thorAnalysisSource = {
  sourceName: "New Rockstars-style Thor Analysis",
  sourceType: "analysis",
  reliability: "interpretive_context",
  rules: {
    canonFacts: "Verify against Marvel.com",
    productionMetadata: "Verify against IMDb",
    theories: "Label as theory or analysis",
  },
  timeline: [
    {
      period: "2011",
      from: 2011,
      to: 2011,
      era: "Origin",
      character: "Thor Odinson",
      systemRole: "ARROGANT_GOD_THOR",
      sourceTag: "analysis",
      movies: ["Thor (2011)"],
      summary: "Thor begins as an arrogant Asgardian prince, then loses his power and learns humility before becoming worthy of Mjolnir again.",
      themes: ["humility", "worthiness", "power vs responsibility", "growth through loss"],
    },
    {
      period: "2012-2015",
      from: 2012,
      to: 2016,
      era: "Warrior",
      character: "Thor",
      systemRole: "WARRIOR_THOR",
      sourceTag: "analysis",
      movies: ["The Avengers (2012)", "Thor: The Dark World (2013)", "Avengers: Age of Ultron (2015)"],
      summary: "Thor becomes a core Avenger and cosmic protector, still shaped by Asgardian honor while slowly moving from warrior prince toward responsible leader.",
      themes: ["duty", "brotherhood", "protection of realms", "honor"],
    },
    {
      period: "2017",
      from: 2017,
      to: 2017,
      era: "Ragnarok",
      character: "Thor",
      systemRole: "REBORN_THOR",
      sourceTag: "analysis",
      movies: ["Thor: Ragnarok (2017)"],
      summary: "Thor loses Mjolnir, Odin, Asgard, and part of his old identity, forcing him to discover that his worth comes from within rather than from titles or weapons.",
      themes: ["identity beyond power", "loss", "transformation", "inner power vs external tools"],
    },
    {
      period: "2018-2019",
      from: 2018,
      to: 2023,
      era: "Trauma",
      character: "Thor",
      systemRole: "TRAUMA_THOR",
      sourceTag: "analysis",
      movies: ["Avengers: Infinity War (2018)", "Avengers: Endgame (2019)"],
      summary: "Thor carries enormous grief after failing to stop Thanos, making this phase about guilt, depression, and the struggle to recover a sense of purpose.",
      themes: ["failure", "guilt", "depression", "loss of purpose"],
    },
    {
      period: "2022",
      from: 2024,
      to: 2025,
      era: "Rediscovery",
      character: "Thor",
      systemRole: "REDISCOVERED_THOR",
      sourceTag: "analysis",
      movies: ["Thor: Love and Thunder (2022)"],
      summary: "Thor reconnects with love, grief, and care through Jane Foster and Gorr's daughter, shifting from revenge-driven warrior toward protector and mentor.",
      themes: ["love", "purpose", "emotional growth", "protecting others beyond battle"],
    },
    {
      period: "Post-2022",
      from: 2026,
      to: 2027,
      era: "Legacy",
      character: "Thor",
      systemRole: "LEGACY_THOR",
      sourceTag: "analysis",
      movies: [],
      summary: "Thor moves further away from being only a king or warrior and becomes a guardian figure, balancing godlike power with human connection and wisdom.",
      themes: ["legacy", "fatherhood", "balance", "wisdom"],
    },
  ],
  coreModel: {
    sourceTag: "analysis",
    identity: "A god who learns to be human through loss, failure, and love.",
    structure: "Mythological hero evolving into emotional protector.",
    themes: ["worthiness", "identity", "loss", "transformation", "purpose", "love", "legacy"],
    narrativePatterns: ["arrogance to humility", "power loss to self-discovery", "external identity to internal identity", "failure to growth", "warrior to protector to mentor"],
  },
};

export const analysisForThorYear = (year) => thorAnalysisSource.timeline.find((entry) => year >= entry.from && year <= entry.to) ?? null;
