export const whereaboutsIntel = [
  {
    characterName: "Peter Parker / Spider-Man",
    from: 2016,
    to: 2017,
    confidence: "confirmed",
    title: "Queens-based rookie hero under Tony Stark's watch",
    summary: "Peter returns home to Queens after Civil War and tries to balance school, neighborhood crime-fighting, and proving himself to Tony Stark.",
    note: "This range is anchored by Civil War/Homecoming-era MCU appearances.",
    sources: [
      { label: "Marvel: Spider-Man: Homecoming", url: "https://www.marvel.com/movies/spider-man-homecoming" },
      { label: "IMDb: Spider-Man: Homecoming", url: "https://www.imdb.com/title/tt2250912/" },
    ],
  },
  {
    characterName: "Peter Parker / Spider-Man",
    from: 2018,
    to: 2022,
    confidence: "confirmed",
    title: "Snapped after fighting Thanos",
    summary: "Peter joins Tony Stark and Doctor Strange in the fight against Thanos, then is erased by the Snap. For the Blip years, he is not active in the living world.",
    note: "The timeline treats 2018-2022 as the Blip period.",
    sources: [
      { label: "IMDb: Avengers: Infinity War", url: "https://www.imdb.com/title/tt4154756/" },
      { label: "Marvel: Endgame Iron Man refresher", url: "https://www.marvel.com/articles/movies/avengers-endgame-refresher-iron-man" },
    ],
  },
  {
    characterName: "Peter Parker / Spider-Man",
    from: 2023,
    to: 2023,
    confidence: "confirmed",
    title: "Restored and reunited with the Avengers",
    summary: "Peter returns after Hulk reverses the Snap and joins the final battle against Thanos' army. Afterward, he resumes life as a student.",
    note: "This is anchored by Avengers: Endgame's 2023 time jump.",
    sources: [
      { label: "IMDb: Avengers: Endgame plot", url: "https://www.imdb.com/title/tt4154796/plotsummary/" },
      { label: "Marvel: Avengers: Endgame", url: "https://www.marvel.com/movies/avengers-endgame" },
    ],
  },
  {
    characterName: "Peter Parker / Spider-Man",
    from: 2024,
    to: 2025,
    confidence: "inferred",
    title: "Anonymous street-level Spider-Man in New York",
    summary: "After the multiverse crisis, Peter chooses a spell that makes the world forget Peter Parker. The best read is that he remains in New York, operating alone as Spider-Man.",
    note: "The exact day-to-day whereabouts are inferred from No Way Home's ending and the app's New York location clue.",
    sources: [
      { label: "IMDb: Spider-Man: No Way Home plot", url: "https://www.imdb.com/title/tt10872600/plotsummary/" },
      { label: "Marvel: Spider-Man character page", url: "https://www.marvel.com/characters/spider-man-peter-parker" },
    ],
  },
  {
    characterName: "Peter Parker / Spider-Man",
    from: 2026,
    to: 2026,
    confidence: "planned",
    title: "Planned return in Spider-Man: Brand New Day",
    summary: "Peter is expected to return as a more independent, street-level Spider-Man in a New York City that no longer knows his civilian identity.",
    note: "This is a planned release, so the exact in-universe year may still shift once the movie is out.",
    sources: [
      { label: "Marvel: Spider-Man: Brand New Day", url: "https://www.marvel.com/movies/spider-man-brand-new-day" },
      { label: "IMDb: Spider-Man: Brand New Day", url: "https://www.imdb.com/title/tt22084616/" },
    ],
  },
  {
    characterName: "Tony Stark / Iron Man",
    from: 2010,
    to: 2011,
    confidence: "confirmed",
    title: "Publicly active as Iron Man",
    summary: "Tony Stark becomes Iron Man after escaping captivity and later operates publicly while facing government and personal pressure around the armor.",
    note: "This range covers Iron Man and Iron Man 2 in the app timeline.",
    sources: [
      { label: "IMDb: Iron Man", url: "https://www.imdb.com/title/tt0371746/" },
      { label: "IMDb: Iron Man 2", url: "https://www.imdb.com/title/tt1228705/" },
    ],
  },
  {
    characterName: "Tony Stark / Iron Man",
    from: 2012,
    to: 2014,
    confidence: "confirmed",
    title: "Avenger operating from New York and Stark/Avengers facilities",
    summary: "Tony helps defend New York during the Avengers' first public battle, then spends the aftermath dealing with trauma and refining his role as a core Avenger.",
    note: "The app uses Avengers operations as his broad location clue.",
    sources: [
      { label: "IMDb: The Avengers", url: "https://www.imdb.com/title/tt0848228/" },
      { label: "IMDb: Iron Man 3", url: "https://www.imdb.com/title/tt1300854/" },
    ],
  },
  {
    characterName: "Tony Stark / Iron Man",
    from: 2015,
    to: 2017,
    confidence: "confirmed",
    title: "Avengers leader, Sokovia Accords supporter, and Peter's mentor",
    summary: "Tony creates Ultron with Bruce Banner, deals with the consequences of Sokovia, supports oversight through the Accords, and brings Peter Parker into the superhero world.",
    note: "His whereabouts move between Avengers operations, the Civil War conflict, and Peter's Queens storyline.",
    sources: [
      { label: "IMDb: Avengers: Age of Ultron", url: "https://www.imdb.com/title/tt2395427/" },
      { label: "IMDb: Captain America: Civil War", url: "https://www.imdb.com/title/tt3498820/" },
      { label: "Marvel: Spider-Man: Homecoming", url: "https://www.marvel.com/movies/spider-man-homecoming" },
    ],
  },
  {
    characterName: "Tony Stark / Iron Man",
    from: 2018,
    to: 2022,
    confidence: "confirmed",
    title: "Survivor of the Snap after the Titan battle",
    summary: "Tony fights Thanos off-world, loses Peter to the Snap, and survives into the five-year Blip period.",
    note: "This period is framed by the aftermath of the Titan battle and Tony's separation from the heroes left on Earth.",
    sources: [
      { label: "Marvel: Endgame Iron Man refresher", url: "https://www.marvel.com/articles/movies/avengers-endgame-refresher-iron-man" },
      { label: "IMDb: Avengers: Infinity War", url: "https://www.imdb.com/title/tt4154756/" },
    ],
  },
  {
    characterName: "Tony Stark / Iron Man",
    from: 2023,
    to: 2027,
    confidence: "confirmed",
    title: "Sacrifices himself during the final battle",
    summary: "Tony helps solve time travel, joins the final battle, and dies after using the Infinity Stones to defeat Thanos and his army.",
    note: "After 2023, Tony's physical whereabouts are no longer active; his role is legacy and memorial.",
    sources: [
      { label: "IMDb: Avengers: Endgame plot", url: "https://www.imdb.com/title/tt4154796/plotsummary/" },
      { label: "Marvel: Avengers: Endgame", url: "https://www.marvel.com/movies/avengers-endgame" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 1942,
    to: 1945,
    confidence: "confirmed",
    title: "World War II Captain America",
    summary: "Steve Rogers becomes Captain America and fights during World War II before crashing into the ice.",
    note: "This is anchored by Captain America: The First Avenger.",
    sources: [
      { label: "IMDb: Captain America: The First Avenger", url: "https://www.imdb.com/title/tt0458339/" },
      { label: "Marvel: Captain America character page", url: "https://www.marvel.com/characters/captain-america-steve-rogers" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 1946,
    to: 2010,
    confidence: "confirmed",
    title: "Frozen and missing from public life",
    summary: "Steve is frozen after World War II, so he is not active in the modern MCU until S.H.I.E.L.D. recovers him.",
    note: "The app treats this long period as inactive but physically preserved in ice.",
    sources: [
      { label: "IMDb: Captain America: The First Avenger", url: "https://www.imdb.com/title/tt0458339/" },
      { label: "Marvel: Captain America character page", url: "https://www.marvel.com/characters/captain-america-steve-rogers" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 2011,
    to: 2013,
    confidence: "confirmed",
    title: "Recovered by S.H.I.E.L.D. and active with the Avengers",
    summary: "Steve is found in the ice, adjusts to the modern world, and helps lead the Avengers during the Battle of New York.",
    note: "The app uses S.H.I.E.L.D./Avengers operations as his broad location clue.",
    sources: [
      { label: "IMDb: The Avengers", url: "https://www.imdb.com/title/tt0848228/" },
      { label: "Marvel: Captain America character page", url: "https://www.marvel.com/characters/captain-america-steve-rogers" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 2014,
    to: 2015,
    confidence: "confirmed",
    title: "Exposes HYDRA and remains a field Avenger",
    summary: "Steve works with Natasha and Fury as S.H.I.E.L.D. collapses, then continues with the Avengers through the Ultron/Sokovia crisis.",
    note: "This range covers The Winter Soldier and Age of Ultron.",
    sources: [
      { label: "IMDb: Captain America: The Winter Soldier", url: "https://www.imdb.com/title/tt1843866/" },
      { label: "IMDb: Avengers: Age of Ultron", url: "https://www.imdb.com/title/tt2395427/" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 2016,
    to: 2017,
    confidence: "confirmed",
    title: "Fugitive after opposing the Sokovia Accords",
    summary: "Steve rejects the Accords, clashes with Tony, and goes off-grid after the Avengers split.",
    note: "This is anchored by Captain America: Civil War and its aftermath.",
    sources: [
      { label: "IMDb: Captain America: Civil War", url: "https://www.imdb.com/title/tt3498820/" },
      { label: "Marvel: Captain America character page", url: "https://www.marvel.com/characters/captain-america-steve-rogers" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 2018,
    to: 2022,
    confidence: "confirmed",
    title: "Survivor of the Snap",
    summary: "Steve survives Infinity War and continues through the Blip years as one of the remaining Avengers.",
    note: "His exact daily movements during the Blip are inferred from Endgame's surviving-Avengers setup.",
    sources: [
      { label: "IMDb: Avengers: Infinity War", url: "https://www.imdb.com/title/tt4154756/" },
      { label: "IMDb: Avengers: Endgame plot", url: "https://www.imdb.com/title/tt4154796/plotsummary/" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 2023,
    to: 2025,
    confidence: "confirmed",
    title: "Returns the Stones and chooses a life in the past",
    summary: "After the final battle, Steve returns the Infinity Stones and Mjolnir, then remains in the past with Peggy Carter before reappearing as an elderly man to pass the shield to Sam Wilson.",
    note: "After 2023, Steve is not an active present-day Captain America in the app timeline.",
    sources: [
      { label: "IMDb: Avengers: Endgame plot", url: "https://www.imdb.com/title/tt4154796/plotsummary/" },
      { label: "Marvel: Avengers: Endgame", url: "https://www.marvel.com/movies/avengers-endgame" },
    ],
  },
  {
    characterName: "Steve Rogers / Captain America",
    from: 2026,
    to: 2026,
    confidence: "teased",
    title: "Steve Rogers is teased for Avengers: Doomsday",
    summary: "Steve Rogers is teased for a future Avengers return, but the exact role and timeline placement are not public yet.",
    note: "Treat this as a teased future appearance, not a confirmed active present-day status.",
    sources: [
      { label: "Marvel: Avengers: Doomsday", url: "https://www.marvel.com/movies/avengers-doomsday" },
      { label: "IMDb: Avengers: Doomsday", url: "https://www.imdb.com/title/tt21357150/fullcredits/" },
    ],
  },
  {
    characterName: "Bruce Banner / Hulk",
    from: 2026,
    to: 2026,
    confidence: "planned",
    title: "Listed for Spider-Man: Brand New Day",
    summary: "Bruce Banner is currently mapped near Peter Parker's planned 2026 story, making this a future appearance clue rather than a confirmed present-day location.",
    note: "The role is planned, but the story reason and exact in-universe placement are still not public.",
    sources: [
      { label: "IMDb: Spider-Man: Brand New Day", url: "https://www.imdb.com/title/tt22084616/" },
      { label: "Marvel: Spider-Man: Brand New Day", url: "https://www.marvel.com/movies/spider-man-brand-new-day" },
    ],
  },
  {
    characterName: "Thor",
    from: 2026,
    to: 2026,
    confidence: "planned",
    title: "Planned return in Avengers: Doomsday",
    summary: "Thor is planned to return in the next Avengers-scale crisis.",
    note: "The movie's plot is still under wraps, so this confirms a planned appearance more than a precise location.",
    sources: [
      { label: "Marvel: Avengers: Doomsday", url: "https://www.marvel.com/movies/avengers-doomsday" },
      { label: "IMDb: Avengers: Doomsday cast", url: "https://www.imdb.com/title/tt21357150/fullcredits/" },
    ],
  },
  {
    characterName: "Scott Lang / Ant-Man",
    from: 2026,
    to: 2026,
    confidence: "planned",
    title: "Planned return in Avengers: Doomsday",
    summary: "Scott Lang is planned to return in the next Avengers-scale crisis.",
    note: "The appearance is planned, but the story role and in-universe location are still not public.",
    sources: [
      { label: "Marvel: Doomsday begins production", url: "https://www.marvel.com/articles/movies/marvel-studios-avengers-doomsday-begins-production" },
      { label: "IMDb: Avengers: Doomsday cast", url: "https://www.imdb.com/title/tt21357150/fullcredits/cast" },
    ],
  },
  {
    characterName: "Thanos",
    from: 2012,
    to: 2015,
    confidence: "confirmed",
    title: "Cosmic puppet-master behind the Infinity Stone hunt",
    summary: "Thanos is not living on Earth during these years. He is operating from space, using others like Loki and Ronan while moving toward his larger Infinity Stone plan.",
    note: "This range is based on his Avengers, Guardians, and Age of Ultron appearances rather than a normal Earth location.",
    sources: [
      { label: "Marvel: Thanos profile", url: "https://www.marvel.com/characters/thanos/on-screen/profile" },
      { label: "IMDb: Guardians of the Galaxy", url: "https://www.imdb.com/title/tt2015381/" },
    ],
  },
  {
    characterName: "Thanos",
    from: 2018,
    to: 2022,
    confidence: "confirmed",
    title: "Wins the Infinity War, then dies on the Garden planet",
    summary: "Thanos collects the Infinity Stones, performs the Snap, retreats to a remote planet, and is killed by the surviving Avengers after destroying the Stones.",
    note: "During the Blip years, the original Thanos is dead; his impact is what remains active across the universe.",
    sources: [
      { label: "IMDb: Avengers: Infinity War", url: "https://www.imdb.com/title/tt4154756/" },
      { label: "IMDb: Avengers: Endgame plot", url: "https://www.imdb.com/title/tt4154796/plotsummary/" },
    ],
  },
  {
    characterName: "Thanos",
    from: 2023,
    to: 2027,
    confidence: "confirmed",
    title: "A 2014 variant is erased in the final battle",
    summary: "Endgame brings a 2014 version of Thanos into 2023. Tony Stark uses the Stones to erase him and his army, so Thanos has no active present-day whereabouts afterward.",
    note: "Later searches for Thanos should be read as legacy, variant, or multiverse context unless a new project confirms otherwise.",
    sources: [
      { label: "IMDb: Avengers: Endgame", url: "https://www.imdb.com/title/tt4154796/" },
      { label: "Marvel: Thanos profile", url: "https://www.marvel.com/characters/thanos/on-screen/profile" },
    ],
  },
  {
    characterName: "Vision",
    from: 2015,
    to: 2017,
    confidence: "confirmed",
    title: "Synthetic Avenger created during the Ultron crisis",
    summary: "Vision is born from the Mind Stone, J.A.R.V.I.S., and the synthetic body Ultron intended for himself. He becomes an Avenger and later sides with Tony during Civil War.",
    note: "His location is tied to Avengers operations, then the fractured team after the Sokovia Accords.",
    sources: [
      { label: "Marvel: Vision profile", url: "https://www.marvel.com/characters/vision/on-screen/profile" },
      { label: "IMDb: Avengers: Age of Ultron", url: "https://www.imdb.com/title/tt2395427/" },
    ],
  },
  {
    characterName: "Vision",
    from: 2018,
    to: 2022,
    confidence: "confirmed",
    title: "Killed when Thanos takes the Mind Stone",
    summary: "Vision and Wanda hide in Scotland before the fight with Thanos reaches Wakanda. Vision dies when Thanos removes the Mind Stone from his forehead.",
    note: "For the Blip years, the original Vision is not active.",
    sources: [
      { label: "IMDb: Avengers: Infinity War", url: "https://www.imdb.com/title/tt4154756/" },
      { label: "Marvel: Vision profile", url: "https://www.marvel.com/characters/vision/on-screen/profile" },
    ],
  },
  {
    characterName: "Vision",
    from: 2023,
    to: 2025,
    confidence: "confirmed",
    title: "Westview Vision fades; White Vision leaves with restored memories",
    summary: "WandaVision creates a memory-based Vision inside Westview while S.W.O.R.D. activates White Vision. White Vision regains key memories and departs, leaving his next whereabouts unresolved.",
    note: "This is confirmed as a status shift, but his exact location after Westview is not shown.",
    sources: [
      { label: "Marvel: WandaVision", url: "https://www.marvel.com/tv-shows/wandavision/1" },
      { label: "IMDb: WandaVision", url: "https://www.imdb.com/title/tt9140560/" },
    ],
  },
  {
    characterName: "Vision",
    from: 2026,
    to: 2026,
    confidence: "planned",
    title: "Planned focus of VisionQuest",
    summary: "VisionQuest is planned as Vision's next major MCU chapter, with White Vision searching through memory, identity, and what remains of the original Vision.",
    note: "The story placement is projected until the series confirms the exact in-universe timing.",
    sources: [
      { label: "IMDb: VisionQuest", url: "https://www.imdb.com/title/tt31838669/" },
      { label: "Marvel: Vision profile", url: "https://www.marvel.com/characters/vision/on-screen/profile" },
    ],
  },
  {
    characterName: "Shang-Chi",
    from: 2024,
    to: 2025,
    confidence: "confirmed",
    title: "New hero connected to Ta Lo and the Ten Rings",
    summary: "Shang-Chi leaves his hidden life in San Francisco, confronts Wenwu, protects Ta Lo, and ends the film connected to Wong, Banner, and Carol Danvers through the Ten Rings signal.",
    note: "The app treats 2024-2025 as his active post-origin period while the next exact placement waits for future projects.",
    sources: [
      { label: "Marvel: Shang-Chi profile", url: "https://www.marvel.com/characters/shang-chi/on-screen/profile" },
      { label: "IMDb: Shang-Chi", url: "https://www.imdb.com/title/tt9376612/" },
    ],
  },
  {
    characterName: "Shang-Chi",
    from: 2026,
    to: 2026,
    confidence: "planned",
    title: "Planned return in Avengers: Doomsday",
    summary: "Shang-Chi is mapped as a planned returning hero for the next Avengers chapter.",
    note: "The role is planned, but the exact story location is not public yet.",
    sources: [
      { label: "Marvel: Doomsday begins production", url: "https://www.marvel.com/articles/movies/marvel-studios-avengers-doomsday-begins-production" },
      { label: "IMDb: Avengers: Doomsday cast", url: "https://www.imdb.com/title/tt21357150/fullcredits/cast" },
    ],
  },
];
